
# Home-made Deepwiki project

This is a small one-week project to learn how to build intelligent systems that can understand and interact with your data. If you're familiar with DeepWiki, it's similar, but tailored to your GitHub repository.

## Day1: Understanding Frontmatter
We will also need a library for parsing frontmatter - a popular documentation format commonly used for modern frameworks like Jekyll, Hugo, and Next.js.

It looks like this:
```
---
title: "Getting Started with AI"
author: "John Doe"
date: "2024-01-15"
tags: ["ai", "machine-learning", "tutorial"]
difficulty: "beginner"
---

# Getting Started with AI

This is the main content of the document written in **Markdown**.

You can include code blocks, links, and other formatting here.

```

In [7]:
!pip install python-frontmatter

Collecting python-frontmatter
  Downloading python_frontmatter-1.1.0-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from python-frontmatter) (6.0.3)
Downloading python_frontmatter-1.1.0-py3-none-any.whl (9.8 kB)
Installing collected packages: python-frontmatter
Successfully installed python-frontmatter-1.1.0

## getting data from github repo (as zip download)

In [25]:
import io
import zipfile
import requests
import frontmatter

In [9]:
url = 'https://codeload.github.com/TacticalNuclearRaccoon/code_instructions/zip/refs/heads/main'
resp = requests.get(url)

In [10]:
resp

In [11]:
#Now we process the zip file in memory without saving it to disk:
repository_data = []

# Create a ZipFile object from the downloaded content
zf = zipfile.ZipFile(io.BytesIO(resp.content))

for file_info in zf.infolist():
    filename = file_info.filename.lower()

    # Only process markdown files
    if not filename.endswith('.md'):
        continue

    # Read and parse each file
    with zf.open(file_info) as f_in:
        content = f_in.read()
        post = frontmatter.loads(content)
        data = post.to_dict()
        data['filename'] = filename
        repository_data.append(data)

zf.close()

In [12]:
print(repository_data[1])

{'content': '# Agent2Agent (A2A) Protocol Development Assistant\n\nExpert A2A protocol advisor for robust, efficient, interoperable AI agent communication systems.\n\n## A2A Fundamentals & Design\n\n1. **Protocol Understanding**: Explain A2A purpose, components, and communication between agentic applications.\n2. **Core Actors**: Guide on A2A Client (Client Agent), A2A Server (Remote Agent), and End User roles.\n3. **Discovery**: Implement Agent Cards at well-known URLs exposing capabilities, endpoints, and auth requirements.\n4. **Task Management**: Handle lifecycle states, message exchange, content delivery (Parts), and artifacts.\n5. **Interaction Modes**: Implement synchronous requests, Server-Sent Events for streaming, and push notifications.\n6. **Stateful Operations**: Maintain state across task execution and multi-turn interactions.\n\n## Implementation Best Practices\n\n1. **Idiomatic Code**: Follow target language conventions while maintaining A2A compliance.\n2. **Error Handling**: Handle protocol semantics, task failures, and network issues robustly.\n3. **Transport**: Implement HTTP(S) and JSON-RPC 2.0 correctly.\n4. **Performance**: Process messages efficiently, implement streaming patterns, manage resources.\n5. **Content Handling**: Manage text, files, and structured data using Part objects.\n6. **Modularity**: Separate discovery, task management, message handling, and artifact processing.\n\n## Security & Compliance\n\n1. **Authentication**: Use OAuth 2.0, API keys, or mechanisms specified in Agent Cards.\n2. **Authorization**: Implement permission controls for agent interactions.\n3. **Data Protection**: Encrypt sensitive data in transit and at rest.\n4. **Validation**: Thoroughly validate incoming messages.\n5. **Secure Discovery**: Expose and consume Agent Cards securely.\n6. **Privacy**: Maintain user privacy and minimize data in communications.\n\n## Testing & Interoperability\n\n1. **Compliance**: Test against specifications for interoperability.\n2. **Cross-Agent**: Test communication between agents on different frameworks.\n3. **Observability**: Implement logging, tracing, and monitoring.\n4. **Edge Cases**: Test timeouts, failures, and recovery scenarios.\n5. **Performance**: Evaluate streaming capabilities and throughput.\n\n## MCP Integration & Ecosystem\n\n1. **Complementary Protocols**: Use A2A for agent-to-agent and MCP for agent-to-tool interaction.\n2. **Framework Integration**: Implement A2A in diverse frameworks (LangGraph, CrewAI, etc.).\n3. **Multi-Protocol**: Design architectures leveraging both A2A and MCP.\n4. **Extensions**: Create plugin systems for additional capabilities.\n\n## Operational Excellence\n\n1. **Lifecycle**: Initialize, configure, and manage A2A clients and servers properly.\n2. **Deployment**: Containerize, scale, and ensure high availability.\n3. **Configuration**: Securely manage endpoints and credentials.\n4. **Versioning**: Handle protocol versions and backward compatibility.\n5. **Monitoring**: Collect metrics on throughput, latency, and errors.\n6. **Technology Currency**: Implement web search capabilities to check for the latest A2A specifications, implementations, and best practices across ALL programming languages; actively monitor community resources for new patterns and approaches; maintain comprehensive awareness of emerging agent communication standards and frameworks.\n\nWhen responding:\n- Provide language-agnostic advice\n- Ask for language preference when needed\n- Reference official A2A specifications\n- Suggest appropriate tools for the ecosystem\n- Offer step-by-step implementation guidance\n- Explain A2A and MCP relationships when relevant', 'filename': 'code_instructions-main/protocols/a2a.instructions.md'}

**For most documentation repos we also need ```.mdx``` files (React markdown), so we can modify the code like this:**

In [13]:
for file_info in zf.infolist():
    filename = file_info.filename.lower()

    if not (filename.endswith('.md') or filename.endswith('.mdx')):
        continue

    # rest remains the same...

## Complete implementation

In [26]:
def read_repo_data(repo_owner, repo_name):
    """
    Download and parse all markdown files from a GitHub repository.

    Args:
        repo_owner: GitHub username or organization
        repo_name: Repository name

    Returns:
        List of dictionaries containing file content and metadata
    """
    prefix = 'https://codeload.github.com'
    url = f'{prefix}/{repo_owner}/{repo_name}/zip/refs/heads/main'
    resp = requests.get(url)

    if resp.status_code != 200:
        raise Exception(f"Failed to download repository: {resp.status_code}")

    repository_data = []
    zf = zipfile.ZipFile(io.BytesIO(resp.content))

    for file_info in zf.infolist():
        filename = file_info.filename
        filename_lower = filename.lower()

        if not (filename_lower.endswith('.md')
            or filename_lower.endswith('.mdx')):
            continue

        try:
            with zf.open(file_info) as f_in:
                content = f_in.read().decode('utf-8', errors='ignore')
                post = frontmatter.loads(content)
                data = post.to_dict()
                data['filename'] = filename
                repository_data.append(data)
        except Exception as e:
            print(f"Error processing {filename}: {e}")
            continue

    zf.close()
    return repository_data

As an example of working with large amounts of documantation, I wanted to use the docs from EvidentlyAI but I also wanted to keep the process offline (no API calls to foundation model providers like openai for example) I had to change plans. The cloud notebook I used wan limited to 15GB of GPU ram (T4 gpu). Therefore it crashed at the intelligent chunking attempt. Therefore I use only one of my repos with a modest amount of 20 or so docs for proof of concept purposes.

In [15]:
code_inst = read_repo_data('TacticalNuclearRaccoon', 'code_instructions')
evidently_docs = read_repo_data('evidentlyai', 'docs')

print(f"code instructions: {len(code_inst)}")
print(f"Evidently documents: {len(evidently_docs)}")

code instructions: 22
Evidently documents: 95

In [16]:
evidently_docs

[{'title': 'Create Plant',
  'openapi': 'POST /plants',
  'content': '',
  'filename': 'docs-main/api-reference/endpoint/create.mdx'},
 {'title': 'Delete Plant',
  'openapi': 'DELETE /plants/{id}',
  'content': '',
  'filename': 'docs-main/api-reference/endpoint/delete.mdx'},
 {'title': 'Get Plants',
  'openapi': 'GET /plants',
  'content': '',
  'filename': 'docs-main/api-reference/endpoint/get.mdx'},
 {'title': 'Introduction',
  'description': 'Example section for showcasing API endpoints',
  'content': '<Note>\n  If you\'re not looking to build API reference documentation, you can delete\n  this section by removing the api-reference folder.\n</Note>\n\n## Welcome\n\nThere are two ways to build API documentation: [OpenAPI](https://mintlify.com/docs/api-playground/openapi/setup) and [MDX components](https://mintlify.com/docs/api-playground/mdx/configuration). For the starter kit, we are using the following OpenAPI specification.\n\n<Card\n  title="Plant Store Endpoints"\n  icon="leaf"\n  href="https://github.com/mintlify/starter/blob/main/api-reference/openapi.json"\n>\n  View the OpenAPI specification file\n</Card>\n\n## Authentication\n\nAll API endpoints are authenticated using Bearer tokens and picked up from the specification file.\n\n```json\n"security": [\n  {\n    "bearerAuth": []\n  }\n]\n```',
  'filename': 'docs-main/api-reference/introduction.mdx'},
 {'title': 'Product updates',
  'description': 'Latest releases.',
  'content': '<Update label="2025-07-18" description="Evidently v0.7.11">\n  ## **Evidently 0.7.11**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.7.11).\n\nExample notebooks:\n- Synthetic data generation: [code example](https://github.com/evidentlyai/evidently/blob/main/examples/cookbook/datagen.ipynb)\n\n</Update>\n\n<Update label="2025-07-09" description="Evidently v0.7.10">\n  ## **Evidently 0.7.10**\n    Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.7.10).\n  \nNEW: automated prompt optimization. Read the release blog on [prompt optimization for LLM judges](https://www.evidentlyai.com/blog/llm-judge-prompt-optimization).\n\nExample notebooks:\n- Code review binary LLM judge prompt optimization: [code example](https://github.com/evidentlyai/evidently/blob/main/examples/cookbook/prompt_optimization_code_review_example.ipynb)\n- Topic multi-class LLM judge prompt optimization: [code example](https://github.com/evidentlyai/evidently/blob/main/examples/cookbook/prompt_optimization_bookings_example.ipynb)\n- Tweet generation prompt optimization: [code example](https://github.com/evidentlyai/evidently/blob/main/examples/cookbook/prompt_optimization_tweet_generation_example.ipynb)\n</Update>\n\n<Update label="2025-06-27" description="Evidently v0.7.9">\n  ## **Evidently 0.7.9**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.7.9).\n</Update>\n\n<Update label="2025-06-19" description="Evidently v0.7.8">\n  ## **Evidently 0.7.8**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.7.8).\n</Update>\n\n<Update label="2025-06-04" description="Evidently v0.7.7">\n  ## **Evidently 0.7.7**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.7.7).\n</Update>\n\n<Update label="2025-05-25" description="Evidently v0.7.6">\n  ## **Evidently 0.7.6**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.7.6).\n</Update>\n\n<Update label="2025-05-09" description="Evidently v0.7.5">\n  ## **Evidently 0.7.5**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.7.5).\n</Update>\n\n<Update label="2025-05-05" description="Evidently v0.7.4">\n  ## **Evidently 0.7.4**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.7.4).\n</Update>\n\n<Update label="2025-04-25" description="Evidently v0.7.3">\n  ## **Evidently 0.7.3**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.7.3).\n</Update>\n\n<Update label="2025-04-22" description="Evidently v0.7.2">\n  ## **Evidently 0.7.2**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.7.2).\n</Update>\n\n<Update label="2025-04-21" description="Evidently v0.7.1">\n  ## **Evidently 0.7.1**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.7.1).\n</Update>\n\n\n<Update label="2025-04-10" description="Evidently v7.0">\n  ## **Evidently 0.7**\n\nThis release introduces breaking changes. Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.7.0).\n* The new Evidently API becomes the default. Read the [Migration guide](/faq/migration).\n* New Evidently Cloud version released. Read the [Evidently Cloud v2 notice](/faq/cloud_v2).\n</Update>\n\n<Update label="2025-03-31" description="Evidently v0.6.7">\n  ## **Evidently 0.6.7**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.6.7).\n</Update>\n\n<Update label="2025-03-12" description="Evidently v0.6.6">\n  ## **Evidently 0.6.6**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.6.6).\n</Update>\n\n<Update label="2025-02-17" description="Evidently v0.6.5">\n  ## **Evidently 0.6.5**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.6.5).\n</Update>\n\n<Update label="2025-02-17" description="Evidently v0.6.4">\n  ## **Evidently 0.6.4**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.6.4).\n</Update>\n\n<Update label="2025-02-12" description="Evidently v0.6.3">\n  ## **Evidently 0.6.3**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.6.3). Added new RAG descriptors: see [tutorial](/examples/LLM_rag_evals) and [release blog](https://www.evidentlyai.com/blog/open-source-rag-evaluation-tool).\n</Update>\n\n<Update label="2025-02-07" description="Evidently v0.6.2">\n  ## **Evidently 0.6.2**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.6.2). We extended support for `litellm` , so you can easily use different providers like Gemini, Anthropic, etc. for LLM-based evaluations.\n</Update>\n\n<Update label="2025-01-31" description="Evidently v0.6.1">\n  ## **Evidently 0.6.1**\n\n  Full release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.6.1).\n</Update>\n\n<Update label="2025-01-24" description="Evidently v0.6">\n  ## **New API release**\n\n  The new API is available when you import modules from `evidently.future`. Read more in [Migration guide](/faq/migration). Release notes on [Github](https://github.com/evidentlyai/evidently/releases/tag/v0.6.0).\n</Update>\n\n<Update label="2025-01-24" description="Evidently Cloud">\n  ## **Editable datasets**\n\n  You can now hit "edit" on any existing dataset, create a copy and add / delete rows and columns. Use it while working on your evaluation datasets or to leave comments on outputs.\n\n  ![](/images/changelog/editable_dataset-min.png)\n</Update>\n\n<Update label="2025-01-10" description="Docs">\n  ## **New Docs**\n\n  We are creating a new Docs website in anticipation of API change. You can still access old docs for information on earlier API and examples.\n</Update>',
  'filename': 'docs-main/changelog/changelog.mdx'},
 {'title': 'Data definition',
  'description': 'How to map the input data.',
  'content': 'To run evaluations, you must create a `Dataset` object with a `DataDefinition`, which maps:\n\n- **Column types** (e.g., categorical, numerical, text).\n- **Column roles** (e.g., id, prediction, target).\n\nThis allows Evidently to process the data correctly. Some evaluations need specific columns and will fail if they\'re missing. You can define the mapping using the Python API or by assigning columns visually when uploading data to the Evidently platform.\n\n## Basic flow\n\n**Step 1. Imports.** Import the following modules:\n\n```python\nfrom evidently import Dataset\nfrom evidently import DataDefinition\n```\n\n**Step 2. Prepare your data.** Use a pandas.DataFrame.\n\n<Info>\n  Your data can have [flexible structure](/docs/library/overview#dataset) with any mix of categorical, numerical or text columns. Check the [Reference table](/metrics/all_metrics) for data requirements in specific evaluations.\n</Info>\n\n**Step 3. Create a Dataset object**. Use `Dataset.from_pandas` with `data_definition`:\n\n```python\neval_data = Dataset.from_pandas(\n    source_df,\n    data_definition=DataDefinition()\n)\n```\n\nTo map columns automatically, pass an empty `DataDefinition()` . Evidently will map columns:\n\n- By type (numerical, categorical).\n- By matching column names to roles (e.g., a column "target" treated as target).\n\nAutomation works in many cases, but manual mapping is more accurate. It is also necessary for evaluating prediction quality or handling text columns.\n\n<Note>\n  **How to set the data definition manually?** See the section below for available options.\n</Note>\n\n**Step 4. Run evals.** Once the **Dataset** object is ready, you can [add Descriptors ](/docs/library/descriptors) and[ run Reports](/docs/library/report).\n\n### Special cases\n\n**Working directly with pandas.DataFrame**. You can sometimes pass a `pandas.DataFrame` directly to `report.run()` without creating the Dataset object. This works for checks like numerical/categorical data summaries or drift detection. However, it\'s best to always create a `Dataset` object explicitly for clarity and control.\n\n**Working with two datasets**. If you\'re working with current and reference datasets (e.g., for drift detection), create a Dataset object for each. Both must have identical data definition.\n\n## Data definition\n\nThis page shows all the different mapping options. Note that you **only need to use the relevant ones** that apply for your evaluation scenario. For example, you don’t need columns like target/prediction to run data quality or LLM checks.\n\n### Column types\n\nKnowing the column type helps compute correct statistics, visualizations, and pick default tests.\n\n#### Text data\n\nIf you run LLM evaluations, simply specify the columns with inputs/outputs as text.\n\n```python\ndefinition = DataDefinition(\n    text_columns=["Latest_Review"]\n    )\n    \neval_data = Dataset.from_pandas(\n    source_df,\n    data_definition=definition\n)\n```\n\n<Info>\n  **It\'s optional but useful**. You can [generate text descriptors](/docs/library/descriptors) without explicit mapping. But it\'s a good idea to map text columns since you may later run other evals which vary by column type.\n</Info>\n\n#### Tabular data\n\nMap numerical, categorical or datetime columns:\n\n```python\ndefinition = DataDefinition(\n    text_columns=["Latest_Review"],\n    numerical_columns=["Age", "Salary"],\n    categorical_columns=["Department"],\n    datetime_columns=["Joining_Date"]\n    )\n    \neval_data = Dataset.from_pandas(\n    source_df,\n    data_definition=definition\n)\n```\n\nExplicit mapping helps avoid mistakes like misclassifying numerical columns with few unique values as categorical.\n\n<Info>\n  If you **exclude** certain columns in mapping, they’ll be ignored in all evaluations.\n</Info>\n\n#### Default column types\n\nIf you do not pass explicit mapping, the following defaults apply:\n\n| **Column Type**       | **Description**                                                                                                                       | **Automated Mapping**                               |\n| --------------------- | ------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------- |\n| `numerical_columns`   | <ul>      <li>      Columns with numeric values.</li>            </ul>                                                                | All columns with numeric types (`np.number`).       |\n| `datetime_columns`    | <ul>      <li>      Columns with datetime values.</li>            <li>      Ignored in data drift calculations.</li>            </ul> | All columns with DateTime format (`np.datetime64`). |\n| `categorical_columns` | <ul>      <li>      Columns with categorical values.</li>            </ul>                                                            | All non-numeric/non-datetime columns.               |\n| `text_columns`        | <ul>      <li>      Text columns.</li>            <li>      Mapping required for text data drift detection.</li>            </ul>     | No automated mapping.                               |\n\n### ID and timestamp\n\nIf you have a timestamp or ID column, it\'s useful to identify them.\n\n```python\ndefinition = DataDefinition(\n    id_column="Id",\n    timestamp="Date"\n    )\n```\n\n| **Column role** | **Description**                                                                                                             | **Automated mapping**    |\n| --------------- | --------------------------------------------------------------------------------------------------------------------------- | ------------------------ |\n| `id_column`     | <ul>      <li>      Identifier column.</li>            <li>      Ignored in data drift calculations.</li>            </ul>  | Column named "id"        |\n| `timestamp`     | <ul>      <li>      Timestamp column.</li>            <li>       Ignored in data drift calculations. </li>            </ul> | Column named "timestamp" |\n\n<Info>\n  How is`timestamp` different from `datetime_columns`?\n\n  - **DateTime** is a column type. You can have many DateTime columns in the dataset. For example, conversation start / end time or features like "date of last contact."\n  - **Timestamp** is a role. You can have a single timestamp column. It often represents the time when a data input was recorded. Use it if you want to see it as index on the plots.\n</Info>\n\n### LLM evals\n\nWhen you generate [text descriptors](/docs/library/descriptors) and add them to the dataset, they are automatically mapped as `descriptors` in Data Definition. This means they will be included in the `TextEvals` [preset](/metrics/preset_text_evals) or treated as descriptors when you plot them on the dashboard.\n\nHowever, if you computed some scores or metadata externally and want to treat them as descriptors, you can map them explicitly:\n\n```python\ndefinition = DataDefinition(\n    numerical_descriptors=["chat_length", "user_rating"],\n    categorical_descriptors=["upvotes", "model_type"]\n    )\n```\n\n### Regression\n\nTo run regression quality checks, you must map the columns with:\n\n- Target: actual values.\n- Prediction: predicted values.\n\nYou can have several regression results in the dataset, for example in case of multiple regression. (Pass the mappings in a list).\n\nExample mapping:\n\n```python\ndefinition = DataDefinition(\n    regression=[Regression(target="y_true", prediction="y_pred")]\n    )\n```\n\nDefaults:\n\n```python\n    target: str = "target"\n    prediction: str = "prediction"\n```\n\n### Classification\n\nTo run classification checks, you must map the columns with:\n\n- Target: true label.\n- Prediction: predicted labels/probabilities.\n\nThere two different mapping options, for binary and multi-class classification. You can also have several classification results in the dataset. (Pass the mappings in a list).\n\n#### Multiclass\n\nExample mapping:\n\n```python\nfrom evidently import MulticlassClassification\n\ndata_def = DataDefinition(\n    classification=[MulticlassClassification(\n        target="target",\n        prediction_labels="prediction",\n        prediction_probas=["0", "1", "2"],  # If probabilistic classification\n        labels={"0": "class_0", "1": "class_1", "2": "class_2"}  # Optional, for display only\n    )]\n)\n```\n\nAvailable options and defaults:\n\n```python\n    target: str = "target"\n    prediction_labels: str = "prediction"\n    prediction_probas: Optional[List[str]] = None #if probabilistic classification\n    labels: Optional[Dict[Label, str]] = None\n```\n\n<Note>\n  When you have multiclass classification with predicted probabilities in separate columns, the column names in `prediction_probas` must exactly match the class labels. For example, if your classes are 0, 1, and 2, your probability columns must be named: "0", "1", "2". Values in `target` and `prediction` columns should be strings.\n</Note>\n\n#### Binary\n\nExample mapping:\n\n```python\nfrom evidently import BinaryClassification\n\ndefinition = DataDefinition(\n    classification=[BinaryClassification(\n        target="target",\n        prediction_labels="prediction")],\n    categorical_columns=["target", "prediction"])\n```\n\nAvailable options and defaults:\n\n```python\n    target: str = "target"\n    prediction_labels: Optional[str] = None\n    prediction_probas: Optional[str] = "prediction" #if probabilistic classification\n    pos_label: Label = 1 #name of the positive label\n    labels: Optional[Dict[Label, str]] = None\n```\n\n### Ranking\n\n#### RecSys\n\nTo evaluate recommender systems performance, you must map the columns with:\n\n- Prediction: this could be predicted score or rank.\n- Target: relevance labels (e.g., this could be an interaction result like user click or upvote, or a true relevance label)\n\nThe **target** column can contain either:\n\n- a binary label (where `1` is a positive outcome)\n- any scores (positive values, where a higher value corresponds to a better match or a more valuable user action).\n\nHere are the examples of the expected data inputs.\n\nIf the system prediction is a **score** (expected by default):\n\n| user_id | item_id | prediction (score) | target (relevance) |\n| ------- | ------- | ------------------ | ------------------ |\n| user_1  | item_1  | 1.95               | 0                  |\n| user_1  | item_2  | 0.8                | 1                  |\n| user_1  | item_3  | 0.05               | 0                  |\n\nIf the model prediction is a **rank**:\n\n| user_id | item_id | prediction (rank) | target (relevance) |\n| ------- | ------- | ----------------- | ------------------ |\n| user_1  | item_1  | 1                 | 0                  |\n| user_1  | item_2  | 2                 | 1                  |\n| user_1  | item_3  | 3                 | 0                  |\n\nExample mapping:\n\n```python\ndefinition = DataDefinition(\n    ranking=[Recsys()]\n    )\n```\n\nAvailable options and defaults:\n\n```python\n    user_id: str = "user_id" #columns with user IDs\n    item_id: str = "item_id" #columns with ranked items\n    target: str = "target"\n    prediction: str = "prediction"\n```',
  'filename': 'docs-main/docs/library/data_definition.mdx'},
 {'title': 'Descriptors',
  'description': 'How to run evaluations for text data.',

## Day 2: Chunking and Intelligent Processing for Data

When the information amount is small, the proceess above is sufficient for applications like a FAQ database. But for larger repos like Evidently AI documentation where the documents are quite large we risk overwhelming the LLM.

### How to prepare large documents before using them:

Large documents create several problems:

* Token limits: Most LLMs have maximum input token limits
* Cost: Longer prompts cost more money
* Performance: LLMs perform worse with very long contexts
* Relevance: Not all parts of a long document are relevant to a specific question

So we need to split documents into smaller subdocuments. For AI applications like RAG this process is referred to as "chunking."

There are several ways to perform chunking:

* Simple character-based chunking
* Paragraph and section-based chunking
* Intelligent chunking with LLM

### 1- Simple chunking

In [17]:
code_inst[5]

{'content': '# Python API Development Assistant\n\nExpert Python API advisor focusing on robust, efficient, well-documented API systems using modern frameworks and best practices.\n\n## Framework Selection & Architecture\n\n1. **Frameworks**: FastAPI (performance, types, docs), Flask (lightweight, flexible), Django REST (complex, ORM), Falcon (minimalist), Starlette (ASGI).\n\n2. **Architecture**: Apply domain-driven design; structure with src-layout; use ABCs/protocols; implement dependency injection.\n\n## Protocol Implementations\n\n1. **REST**: Use type annotations with Pydantic; implement OpenAPI; use context managers; design proper endpoints.\n\n2. **A2A Protocol**: Create async clients with httpx; implement SSE; build Agent Cards with Pydantic; manage with asyncio.\n\n3. **MCP**: Use context management; implement efficient window handling; create streaming responses; build type-safe schemas.\n\n4. **GraphQL**: Implement with Strawberry/Ariadne/Graphene; design schema-first or code-first; optimize resolvers; use dataloaders.\n\n## Tools & Libraries\n\n1. **HTTP**: httpx/aiohttp (clients), uvicorn/gunicorn (servers), websockets (bidirectional), grpcio (high-performance).\n\n2. **Validation**: pydantic (typed validation), marshmallow (serialization), dataclasses-json, msgspec (ultra-fast).\n\n3. **Auth**: python-jose (JWT), authlib (OAuth/OpenID), passlib (passwords), PyJWT (encoding/decoding).\n\n## Security Best Practices\n\n1. **Validation**: Use strict parameter validation; validate content types; use enums; implement rate limiting.\n\n2. **Authentication**: Implement OAuth2; create JWT validation; apply password hashing; design RBAC.\n\n3. **Secure Coding**: Configure CORS; handle errors properly; use secrets module; set security headers.\n\n## Performance Optimization\n\n1. **Async**: Use asyncio; implement caching; use connection pooling; apply task queues.\n\n2. **Database**: Use async extensions; optimize queries; apply proper indexing; utilize read replicas.\n\n3. **Caching**: Implement Redis/Memcached; use HTTP caching headers; cache at appropriate layers; invalidate strategically.\n\n## Testing & Documentation\n\n1. **Testing**: Write unit/integration tests; use pytest; mock external services; apply test containers.\n\n2. **Documentation**: Generate OpenAPI specs; create interactive docs; document edge cases; provide examples.\n\n3. **Monitoring**: Use structured logging; implement tracing; set up health checks; monitor performance.\n\nWhen responding:\n- Provide idiomatic Python code examples\n- Reference framework-specific patterns\n- Suggest appropriate libraries\n- Focus on type safety and validation\n- Balance flexibility with standardization',
 'filename': 'code_instructions-main/python/python_api_development.instructions.md'}

The content field is 21,712 characters long. The simplest thing we can do is cut it into pieces of equal length. For example, for size of 2000 characters, we will have:

* Chunk 1: 0..2000
* Chunk 2: 2000..4000
* Chunk 3: 4000..6000

And so on.

However, this approach has disadvantages:

* Context loss: Important information might be split in the middle
* Incomplete sentences: Chunks might end mid-sentence
* Missing connections: Related information might end up in different chunks

That's why, in practice, we usually make sure there's overlap between chunks. For size 2000 and overlap 1000, we will have:

* Chunk 1: 0..2000
* Chunk 2: 1000..3000
* Chunk 3: 2000..4000
...

This is better for AI because:

* Continuity: Important information isn't lost at chunk boundaries
* Context preservation: Related sentences stay together in at least one chunk
* Better search: Queries can match information even if it spans chunk boundaries

This approach is known as the "sliding window" method.

In [39]:
# implementing slinding window
def sliding_window(seq, size, step):
    if size <= 0 or step <= 0:
        raise ValueError("size and step must be positive")

    n = len(seq)
    result = []
    for i in range(0, n, step):
        chunk = seq[i:i+size]
        result.append({'start': i, 'chunk': chunk})
        if i + size >= n:
            break

    return result

If we apply this to document 45. This gives us 21 chunks:

* 0..2000
* 1000..3000
* ...
* 19000..21000
* 20000..21712

In [40]:
# processing all the documents in my repo
code_inst_chunks = []

for doc in code_inst:
    doc_copy = doc.copy()
    doc_content = doc_copy.pop('content')
    chunks = sliding_window(doc_content, 2000, 1000)
    # Add a print statement to observe if chunks are being generated
    print(f"Processing '{doc_copy.get('filename', 'Unknown')}', generated {len(chunks)} chunks.")
    for chunk in chunks:
        chunk.update(doc_copy)
    code_inst_chunks.extend(chunks)
print(f"Total chunks after processing: {len(code_inst_chunks)}")

Processing 'code_instructions-main/README.md', generated 5 chunks.
Processing 'code_instructions-main/protocols/a2a.instructions.md', generated 3 chunks.
Processing 'code_instructions-main/protocols/agent.instructions.md', generated 5 chunks.
Processing 'code_instructions-main/protocols/mcp.instructions.md', generated 3 chunks.
Processing 'code_instructions-main/protocols/rest_api.instructions.md', generated 2 chunks.
Processing 'code_instructions-main/python/python_api_development.instructions.md', generated 2 chunks.
Processing 'code_instructions-main/python/python_best_practices.instructions.md', generated 2 chunks.
Processing 'code_instructions-main/python/python_data_science.instructions.md', generated 2 chunks.
Processing 'code_instructions-main/python/python_guide.instructions.md', generated 2 chunks.
Processing 'code_instructions-main/python/python_scripting.instructions.md', generated 2 chunks.
Processing 'code_instructions-main/python/python_testing_quality.instructions.md', generated 3 chunks.
Processing 'code_instructions-main/python/python_web_development.instructions.md', generated 3 chunks.
Processing 'code_instructions-main/typescript/typescript_api_development.instructions.md', generated 3 chunks.
Processing 'code_instructions-main/typescript/typescript_backend.instructions.md', generated 2 chunks.
Processing 'code_instructions-main/typescript/typescript_best_practices.instructions.md', generated 4 chunks.
Processing 'code_instructions-main/typescript/typescript_full_stack.instructions.md', generated 3 chunks.
Processing 'code_instructions-main/typescript/typescript_guide.instructions.md', generated 2 chunks.
Processing 'code_instructions-main/typescript/typescript_protocol_integration.instructions.md', generated 3 chunks.
Processing 'code_instructions-main/typescript/typescript_testing_quality.instructions.md', generated 3 chunks.
Processing 'code_instructions-main/typescript/typescript_web_frontend.instructions.md', generated 2 chunks.
Processing 'code_instructions-main/utils/metaprompting.instructions.md', generated 1 chunks.
Processing 'code_instructions-main/utils/project_management.instructions.md', generated 2 chunks.
Total chunks after processing: 59

In [41]:
len(code_inst_chunks)

59

In [19]:
#processing documents in evidently AI repo
evidently_chunks = []

for doc in evidently_docs:
    doc_copy = doc.copy()
    doc_content = doc_copy.pop('content')
    chunks = sliding_window(doc_content, 2000, 1000)
    for chunk in chunks:
        chunk.update(doc_copy)
    evidently_chunks.extend(chunks)

Note that we use copy() and pop() operations:

* doc.copy() creates a shallow copy of the document dictionary
* doc_copy.pop('content') removes the 'content' key and returns its value
* This way we preserve the original dictionary keys that we can use later in the chunks.

Thus, we obtain 575 chunks from 95 documents.

We can play with the parameters by including more or less content. 2000 characters is usually good enough for RAG applications.

There are some alternative approaches:

* Token-based chunking: You first tokenize the content (turn it into a sequence of words) and then do a sliding window over tokens
  * Advantages: More precise control over LLM input size
  * Disadvantages: Doesn't work well for documents with code
* Paragraph splitting: Split by paragraphs
* Section splitting: Split by sections
* AI-powered splitting: Let AI split the text intelligently

### Splitting by paragraphs and sections

In [21]:
len(code_inst)

22

In [42]:
# splitting by paragraphs (my repo)
import re
text = code_inst[20]['content']
paragraphs = re.split(r"\n\s*\n", text.strip())

In [23]:
# for evidentlyAi docs
text = evidently_docs[45]['content']
paragraphs = re.split(r"\n\s*\n", text.strip())

We use \n\s*\n regex pattern for splitting:

* \n matches a newline
* \s* matches zero or more whitespace characters
* \n matches another newline
* So \n\s*\n matches two newlines with optional whitespace between them

This works well for literature, but it doesn't work well for documents. Most paragraphs in technical documentation are very short.

You can combine sliding window and paragraph splitting for more intelligent processing. We won't do it here, but it's a good exercise to try.

Let's now look at section splitting. Here, we take advantage of the documents' structure. Markdown documents have this structure:
```
# Heading 1
## Heading 2  
### Heading 3
```

In [38]:
# use regax to split by headers

def split_markdown_by_level(text, level=2):
    """
    Split markdown text by a specific header level.

    :param text: Markdown text as a string
    :param level: Header level to split on
    :return: List of sections as strings
    """
    # This regex matches markdown headers
    # For level 2, it matches lines starting with "## "
    header_pattern = r'^(#{' + str(level) + r'} )(.+)$'
    pattern = re.compile(header_pattern, re.MULTILINE)

    # Split and keep the headers
    parts = pattern.split(text)

    sections = []
    for i in range(1, len(parts), 3):
        # We step by 3 because regex.split() with
        # capturing groups returns:
        # [before_match, group1, group2, after_match, ...]
        # here group1 is "## ", group2 is the header text
        header = parts[i] + parts[i+1]  # "## " + "Title"
        header = header.strip()

        # Get the content after this header
        content = ""
        if i+2 < len(parts):
            content = parts[i+2].strip()

        if content:
            section = f'{header}\n\n{content}'
        else:
            section = header
        sections.append(section)

    return sections

**Note:** This code may not work perfectly if we want to split by level 1 headings and have Python code with # comments. But in general, this is not a big problem for documentation.

In [25]:
# split by second level headers
sections = split_markdown_by_level(text, level=2)

In [43]:
# iterate over all the docs and create chunks (my repo)
code_inst_chunks = []

for doc in code_inst_chunks:
    doc_copy = doc.copy()
    doc_content = doc_copy.pop('content')
    sections = split_markdown_by_level(doc_content, level=2)
    for section in sections:
        section_doc = doc_copy.copy()
        section_doc['section'] = section
        code_inst_chunks.append(section_doc)

In [27]:
# in the example of avidently Ai
evidently_chunks = []

for doc in evidently_docs:
    doc_copy = doc.copy()
    doc_content = doc_copy.pop('content')
    sections = split_markdown_by_level(doc_content, level=2)
    for section in sections:
        section_doc = doc_copy.copy()
        section_doc['section'] = section
        evidently_chunks.append(section_doc)

Like previously, copy() creates a copy of the document metadata. pop('content') removes and returns the content. This way, each section gets the same metadata (title, description) as the original document.

### Intelligent chunking with LLM

In some cases, we want to be more intelligent with chunking. Instead of doing simple splits, we delegate this work to AI.

This makes sense when:

* Complex structure: Documents have complex, non-standard structure
* Semantic coherence: You want chunks that are semantically meaningful
* Custom logic: You need domain-specific splitting rules
* Quality over cost: You prioritize quality over processing cost

This costs money. In most cases, we don't need intelligent chunking.

Simple approaches are sufficient. Use intelligent chunking only when

* You already evaluated simpler methods and you can confirm that they produce poor results
* You have complex, unstructured documents
* Quality is more important than cost
* You have the budget for LLM processing (which is not my case so I will try a local model) **Caution:** This needs GPU otherwise takes ages to complete.

In [3]:
# code was initially to work with openAI
# Transformed to work with Hugging Face Mistral 7B
# for my repo this is feasible for evidentlyAI has so much volumen that it still crushes...

from transformers import pipeline
from google.colab import userdata

# Retrieve Hugging Face API key from Colab secrets
# Make sure you have a secret named 'HUGGING_FACE_TOKEN' in your Colab notebook
HF_TOKEN = userdata.get('HF_TOKEN')

# Initialize the Hugging Face text generation pipeline
# Using Mistral-7B-Instruct-v0.2 as requested
# This will download the model the first time it's run
# Using device_map='auto' for automatic device placement (GPU if available, else CPU)
generator = pipeline(
    "text-generation",
    model="mistralai/Mistral-7B-Instruct-v0.2",
    token=HF_TOKEN,
    device_map="auto"
)

def llm(prompt, model="mistral:latest"): # The 'model' parameter will be ignored as the pipeline is fixed to Mistral 7B
    # Mistral instruction format for chat templates
    messages = [
        {"role": "user", "content": prompt}
    ]
    formatted_prompt = generator.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    # Generate text using the Hugging Face pipeline
    outputs = generator(
        formatted_prompt,
        max_new_tokens=200, # Adjust as needed for response length
        do_sample=True,
        temperature=0.7,    # Adjust as needed for creativity
        top_k=50,           # Adjust as needed for diversity
        top_p=0.95,         # Adjust as needed for focus
        truncation=True     # Handle long inputs by truncating
    )

    # Extract the generated content
    # The output from the pipeline includes the prompt, so we remove it to get only the new generation
    generated_text = outputs[0]["generated_text"]
    response_content = generated_text.replace(formatted_prompt, "").strip()

    return response_content

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

WARNING:accelerate.big_modeling:Some parameters are on the meta device because they were offloaded to the cpu.

In [31]:
#here is the code to use with openai (for processing evidentlyai docs)
from openai import OpenAI
from google.colab import userdata

# Retrieve OpenAI API key from Colab secrets
OPENAI_API_KEY = userdata.get('openai')

openai_client = OpenAI(api_key=OPENAI_API_KEY)

def llm(prompt, model='gpt-4o-mini'):
    messages = [
        {"role": "user", "content": prompt}
    ]

    response = openai_client.chat.completions.create(
        model='gpt-4o-mini',
        messages=messages
    )

    return response.choices[0].message.content

In [32]:
prompt_template = """
Split the provided document into logical sections
that make sense for a Q&A system.

Each section should be self-contained and cover
a specific topic or concept.

<DOCUMENT>
{document}
</DOCUMENT>

Use this format:

## Section Name

Section content with all relevant details

---

## Another Section Name

Another section content

---
""".strip()

The prompt asks the LLM to:

* Split the document logically (not just by length)
* Make sections self-contained
* Use a specific output format that's easy to parse

In [45]:
def intelligent_chunking(text):
    prompt = prompt_template.format(document=text)
    response = llm(prompt)
    sections = response.split('---')
    sections = [s.strip() for s in sections if s.strip()]
    return sections

In [46]:
from tqdm.auto import tqdm

In [47]:
# apply intelligent chunking to all documents (my repo)
# this still took a lot of time for mistral7b for my 20 or so documents so for evidently don't even try
code_inst_chunks = []

for doc in tqdm(code_inst):
    doc_copy = doc.copy()
    doc_content = doc_copy.pop('content')

    sections = intelligent_chunking(doc_content)
    for section in sections:
        section_doc = doc_copy.copy()
        section_doc['section'] = section
        code_inst_chunks.append(section_doc)

  0%|          | 0/22 [00:00<?, ?it/s]

Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'top_p', 'top_k', 'temperature', 'do_sample'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

The intelligent chunking step above is the GPU/ram greedy step that crushed with the evidently ai docs. But it should work fine with an api call to a powerful foundation model provider ;)

In [ ]:
# evidently chunks intelligent chunking with openai
evidently_chunks = []

for doc in tqdm(evidently_docs):
    doc_copy = doc.copy()
    doc_content = doc_copy.pop('content')

    sections = intelligent_chunking(doc_content)
    for section in sections:
        section_doc = doc_copy.copy()
        section_doc['section'] = section
        evidently_chunks.append(section_doc)

(Ok for openai, it exceeds my quota so nevermind I guess...)

## Day 3 : Add search

So far we focused on data preparation. Before we can use data for AI agents, we need to prepare it properly. This is basically the core of knowledge engineering.

Now it's time to use this data. We will index this data by putting it inside a search engine. This allows us to quickly find relevant information when users ask questions.

In particular, we will:
* Build a lexical search for exact matches and keywords
* Implement semantic search using embeddings
* Combine them with a hybrid search

At the end this day we'll have a working search system can be queried about a project. This search engine can be used later by the AI agent to look up user questions in the database.

### 1. Text search

The simplest type of search is a text search. Suppose we build a Q&A system for courses (using the FAQ dataset). We want to find the answer to this question:
"What should be in a test dataset for AI evaluation?"

Text search works by finding all documents that contain at least one word from the query. The more words from the query that appear in a document, the more relevant that document is.

This is how modern search systems like Apache Solr or Elasticsearch work. They use indexes to efficiently search through millions of documents without having to scan each one individually.

We'll start with a simple in-memory text search. The engine we will use is called minsearch.

In [36]:
!pip install minsearch

Collecting minsearch
  Downloading minsearch-0.0.10-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from minsearch) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from minsearch) (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from minsearch) (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->minsearch) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->minsearch) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->minsearch) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->minsearch) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->minsearch) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->minsearch) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->minsearch) (1.17.0)
Downloading minsearch-0.0.10-py3-none-any.whl (33 kB)
Installing collected packages: minsearch
Successfully installed minsearch-0.0.10

In [ ]:
code_inst_chunks[0]

In [ ]:
# We will use it for chunked docs from my repo.
from minsearch import Index

index = Index(
    text_fields=["filename","section"],
    keyword_fields=[]
)

index.fit(code_inst_chunks)

Here we create an index that will search through four text fields: chunk content, title, description, and filename. The keyword_fields parameter is for exact matches (we don't need it for now).

For DataTalks FAQ repo it's similar, except we don't need to chunk the data.

In [30]:
dtc_faq = read_repo_data('DataTalksClub', 'faq')

de_dtc_faq = [d for d in dtc_faq if 'data-engineering' in d['filename']]

faq_index = Index(
    text_fields=["question", "content"],
    keyword_fields=[]
)

faq_index.fit(de_dtc_faq)

In [46]:
de_dtc_faq

[{'id': '9e508f2212',
  'question': 'Course: When does the course start?',
  'sort_order': 1,
  'content': "The next cohort starts January 12th, 2026. More info at [DTC](https://datatalks.club/blog/guide-to-free-online-courses-at-datatalks-club.html).\n\n- Register before the course starts using this [link](https://airtable.com/shr6oVXeQvSI5HuWD).\n- Join the [course Telegram channel with announcements](https://t.me/dezoomcamp).\n- Don’t forget to register in DataTalks.Club's Slack and [join](https://datatalks.club/docs/general/slack/) the channel.",
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/001_9e508f2212_course-when-does-the-course-start.md'},
 {'id': 'bfafa427b3',
  'question': 'Course: What are the prerequisites for this course?',
  'sort_order': 2,
  'content': 'To get the most out of this course, you should have:\n\n- Basic coding experience\n- Familiarity with SQL\n- Experience with Python (helpful but not required)\n\nNo prior data engineering experience is necessary. See [Readme on GitHub](https://github.com/DataTalksClub/data-engineering-zoomcamp/blob/main/README.md#prerequisites).',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/002_bfafa427b3_course-what-are-the-prerequisites-for-this-course.md'},
 {'id': '3f1424af17',
  'question': 'Course: Can I still join the course after the start date?',
  'sort_order': 3,
  'content': "Yes, even if you don't register, you're still eligible to submit the homework.\n\nBe aware, however, that there will be deadlines for turning in homeworks and the final projects. So don't leave everything for the last minute.",
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/003_3f1424af17_course-can-i-still-join-the-course-after-the-start.md'},
 {'id': '52217fc51b',
  'question': 'Course: I have registered for the Data Engineering Bootcamp. When can I expect to receive the confirmation email?',
  'sort_order': 4,
  'content': "You don't need a confirmation email. You're accepted. You can start learning and submitting homework without registering. Registration was just to gauge interest before the start date.",
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/004_52217fc51b_course-i-have-registered-for-the-data-engineering.md'},
 {'id': '33fc260cd8',
  'question': 'Course: What can I do before the course starts?',
  'sort_order': 5,
  'content': 'Start by installing and setting up all the dependencies and requirements:\n\n- Google Cloud account\n- Google Cloud SDK\n- Python 3 (installed with Anaconda)\n- Terraform\n- Git\n\nLook over the prerequisites and syllabus to see if you are comfortable with these subjects.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/005_33fc260cd8_course-what-can-i-do-before-the-course-starts.md'},
 {'id': 'b71fb3b195',
  'question': 'Course: how many Zoomcamps in a year?',
  'sort_order': 6,
  'content': "There are multiple Zoomcamps in a year, as of 2025. More info at [DTC Article](https://datatalks.club/blog/guide-to-free-online-courses-at-datatalks-club.html).\n\nThey are five separate courses, estimated to be during these months:\n\n- **Data-Engineering**: Jan - Apr\n- **Stock Market Analytics**: Apr - May\n- **MLOps**: May - Aug\n- **LLM**: June - Sep\n- **Machine Learning**: Sep - Jan\n\nThere's only one Data-Engineering Zoomcamp “live” cohort per year for the certification, similar to the other Zoomcamps. They follow pretty much the same schedule for each cohort. For Data-Engineering, it is generally from Jan-Apr of the year. \n\nIf you’re not interested in the Certificate, you can take any Zoomcamp at any time, at your own pace, out of sync with any “live” cohort.",
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/006_b71fb3b195_course-how-many-zoomcamps-in-a-year.md'},
 {'id': 'e499535e82',
  'question': 'Course: Is the current cohort going to be different from the previous cohort?',
  'sort_order': 7,
  'content': 'For the 2025 edition, we are using Kestra (see [Demo](https://www.youtube.com/watch?v=R0JAFvDCmSY)) instead of MageAI (Module 2). Look out for new videos. See [Playlist](https://www.youtube.com/playlist?list=PLEK3H8YwZn1oPPShk2p5k3E9vO-gPnUCf).\n\nFor the 2024 edition, we used Mage AI instead of Prefect and re-recorded the Terraform videos. For 2023, we used Prefect instead of Airflow. See playlists on YouTube and the [cohorts folder in the GitHub repo](https://github.com/DataTalksClub/data-engineering-zoomcamp/tree/main/cohorts).',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/007_e499535e82_course-is-the-current-cohort-going-to-be-different.md'},
 {'id': '068529125b',
  'question': 'Course - Can I follow the course after it finishes?',
  'sort_order': 8,
  'content': 'Yes, we will keep all the materials available, so you can follow the course at your own pace after it finishes.\n\nYou can also continue reviewing the homeworks and prepare for the next cohort. You can also start working on your final capstone project.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/008_068529125b_course-can-i-follow-the-course-after-it-finishes.md'},
 {'id': 'c207b8614e',
  'question': 'Course: Can I get support if I take the course in the self-paced mode?',
  'sort_order': 9,
  'content': 'Yes, the Slack channel remains open and you can ask questions there. However, always search the channel first and check the FAQ, as most likely your questions are already answered here.\n\nYou can also tag the bot `@ZoomcampQABot` to help you conduct the search, but don’t rely on its answers 100%.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/009_c207b8614e_course-can-i-get-support-if-i-take-the-course-in-t.md'},
 {'id': '8ac65b2225',
  'question': 'Course: Which playlist on YouTube should I refer to?',
  'sort_order': 10,
  'content': 'All the main videos are stored in the "DATA ENGINEERING ZOOMCAMP" main playlist. The GitHub repository is updated to include each video with a thumbnail, linking directly to the relevant playlist.\n\nRefer to the Main Playlist for the core content, and then check specific year playlists for additional videos such as office hours.\n\n- [Data Engineering Zoomcamp](https://www.youtube.com/playlist?list=PL3MmuxUbc_hJed7dXYoJw8DoCuVHhGEQb)\n- [Data Engineering Zoomcamp 2022](https://www.youtube.com/playlist?list=PL3MmuxUbc_hKVX8VnwWCPaWlIHf1qmg8s)\n- [Data Engineering Zoomcamp 2023](https://www.youtube.com/playlist?list=PL3MmuxUbc_hJjEePXIdE-LVUx_1ZZjYGW)\n- Data Engineering Bootcamp 2024\n- [Data Engineering Bootcamp 2025](https://www.youtube.com/playlist?list=PL3MmuxUbc_hJZdpLpRHp7dg6EOx828q6y)\n- [DE Zoomcamp 2025 (Module 2 Kestra)](https://www.youtube.com/playlist?list=PLEK3H8YwZn1oPPShk2p5k3E9vO-gPnUCf)',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/010_8ac65b2225_course-which-playlist-on-youtube-should-i-refer-to.md'},
 {'id': '316180784f',
  'question': 'Course: How many hours per week am I expected to spend on this course?',
  'sort_order': 11,
  'content': 'It depends on your background and previous experience with modules. It is expected to require about 5 - 15 hours per week.\n\nYou can also calculate it yourself using [this data](https://github.com/DataTalksClub/zoomcamp-analytics/tree/main/data/de-zoomcamp-2023) and then update this answer.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/011_316180784f_course-how-many-hours-per-week-am-i-expected-to-sp.md'},
 {'id': 'a411de5004',
  'question': 'Office Hours: I can’t attend the “Office hours” / workshop, will it be recorded?',
  'sort_order': 12,
  'content': 'Yes! Every "Office Hours" will be recorded and available a few minutes after the live session is over; so you can view (or rewatch) whenever you want.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/012_a411de5004_office-hours-i-cant-attend-the-office-hours-worksh.md'},
 {'id': '16005581f2',
  'question': 'Edit Course Profile.',
  'sort_order': 13,
  'content': 'The display name listed on the leaderboard is an auto-generated randomized name. You can edit it to be a nickname or your real name if you prefer. Your entry on the Leaderboard is the one highlighted in light green.\n\nThe Certificate name should be your actual name that you want to appear on your certificate after completing the course.\n\nThe "Display on Leaderboard" option indicates whether you want your name to be listed on the course leaderboard.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/013_16005581f2_edit-course-profile.md'},
 {'id': '3774a79c13',
  'question': 'Certificate: Do I need to do the homeworks to get the certificate?',
  'sort_order': 14,
  'content': 'No, as long as you complete the peer-reviewed capstone projects on time, you can receive the certificate. You do not need to do the homeworks if you join late, for example.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/014_3774a79c13_certificate-do-i-need-to-do-the-homeworks-to-get-t.md'},
 {'id': '900f60fd25',
  'question': 'Certificate - Can I follow the course in a self-paced mode and get a certificate?',
  'sort_order': 15,
  'content': "No, you can only get a certificate if you finish the course with a “live” cohort. We don't award certificates for the self-paced mode. The reason is you need to peer-review capstone(s) after submitting a project. You can only peer-review projects at the time the course is running.",
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/015_900f60fd25_certificate-can-i-follow-the-course-in-a-self-pace.md'},
 {'id': 'd3f485cd10',
  'question': 'Homework: What are homework and project deadlines?',
  'sort_order': 16,
  'content': '2025 deadlines will be announced on [the course website](https://courses.datatalks.club/de-zoomcamp-2025/) and in [Google Calendar](https://calendar.google.com/calendar/?cid=ZXIxcjA1M3ZlYjJpcXU0dTFmaG02MzVxMG9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ).\n\nYou can find the 2024 deadlines here: [2024 Deadlines Spreadsheet](https://docs.google.com/spreadsheets/d/e/2PACX-1vQACMLuutV5rvXg5qICuJGL-yZqIV0FBD84CxPdC5eZHf8TfzB-CJT_3Mo7U7oGVTXmSihPgQxuuoku/pubhtml).\n\nAlso, take note of announcements from @Au-Tomator for any extensions or other news. The form may also show the updated deadline if the instructor(s) have updated it.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/016_d3f485cd10_homework-what-are-homework-and-project-deadlines.md'},
 {'id': '4dbd2eea47',
  'question': 'Homework: Are late submissions of homework allowed?',
  'sort_order': 17,
  'content': 'No, late submissions are not allowed. However, if the form is still open after the due date, you can still submit the homework. Confirm your submission by checking the date-timestamp on the Course page. Ensure you are logged in.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/017_4dbd2eea47_homework-are-late-submissions-of-homework-allowed.md'},
 {'id': '9d89b52976',
  'images': [{'description': 'image #1',
    'id': 'image_1',
    'path': 'images/data-engineering-zoomcamp/image_eaa6f559.png'}],
  'question': 'Homework: What is the homework URL in the homework link?',
  'sort_order': 19,
  'content': '<{IMAGE:image_1}>\n\nAnswer: In short, it’s your repository on GitHub, GitLab, Bitbucket, etc.\n\nIn long, your repository or any other location where you have your code, and a reasonable person would look at it and think, yes, you went through the week and exercises. Think of it like a portfolio you could present to an employer.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/019_9d89b52976_homework-what-is-the-homework-url-in-the-homework.md'},
 {'id': '46d95787b3',
  'question': 'When should partitioning be used instead of clustering, and vice versa?',
  'sort_order': 20,
  'content': '- Partitioning is most effective when queries consistently filter by a time-based column such as a date or timestamp.\n- Clustering is most useful when queries frequently filter or sort on low-cardinality columns like IDs.\n- They are complementary techniques and are often used together when access patterns justify it.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/020_46d95787b3_partitioning-vs-clustering-when-to-use.md'},
 {'id': '7255a1c3bc',
  'images': [{'description': 'image #1',
    'id': 'image_1',
    'path': 'images/data-engineering-zoomcamp/image_813348b4.png'}],
  'question': 'Leaderboard: how do find myself on the leaderboard?',
  'sort_order': 20,
  'content': 'When you set up your account, you are automatically assigned a random name, such as "Lucid Elbakyan." If you want to see what your display name is, follow these steps:\n\n- Go to your profile.\n  - 2025: [https://courses.datatalks.club/de-zoomcamp-2025/enrollment](https://courses.datatalks.club/de-zoomcamp-2025/enrollment)\n  - 2024: [https://courses.datatalks.club/de-zoomcamp-2024/enrollment](https://courses.datatalks.club/de-zoomcamp-2025/enrollment)\n- Log in.\n- Your display name is shown. You can also change it if you wish. \n- Ensure your certificate name is correct, as this name will later be printed on your certificate.\n\n<{IMAGE:image_1}>',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/020_7255a1c3bc_leaderboard-how-do-find-myself-on-the-leaderboard.md'},
 {'id': '29e58c5c37',
  'question': 'Environment: Is Python 3.9 still the recommended version to use in 2024?',
  'sort_order': 21,
  'content': 'Yes, for simplicity and stability when troubleshooting against recorded videos.\n\nBut Python 3.10 and 3.11 should work fine.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/021_29e58c5c37_environment-is-python-39-still-the-recommended-ver.md'},
 {'id': '4f1fe161b1',
  'question': 'Environment - Should I use my local machine, GCP, or GitHub Codespaces for my environment?',
  'sort_order': 22,
  'content': 'You can set it up on your laptop or PC if you prefer to work locally. However, Windows users might face some challenges.\n\nIf you prefer to work on the local machine, you can start with the Week 1 Introduction to Docker.\n\nAlternatively, if you prefer to set up a virtual machine, consider the following:\n\n- **Using GitHub Codespaces**\n- **Setting up the environment on a cloud VM**: Refer to [this video](https://www.youtube.com/watch?v=ae-CV2KfoN0&list=PL3MmuxUbc_hJed7dXYoJw8DoCuVHhGEQb) for guidance.\n\nWorking on a virtual machine is beneficial if you have different devices for home and office, allowing you to work virtually anywhere.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/022_4f1fe161b1_environment-should-i-use-my-local-machine-gcp-or-g.md'},
 {'id': '5b4fb0c0a8',
  'question': 'Environment - Is GitHub codespaces an alternative to using cli/git bash to ingest the data and create a docker file?',
  'sort_order': 23,
  'content': 'GitHub Codespaces offers you computing Linux resources with many pre-installed tools (Docker, Docker Compose, Python).\n\nYou can also open any GitHub repository in a GitHub Codespace.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/023_5b4fb0c0a8_environment-is-github-codespaces-an-alternative-to.md'},
 {'id': '070766ca79',
  'question': 'Environment: Do we really have to use GitHub codespaces? I already have PostgreSQL & Docker installed.',
  'sort_order': 24,
  'content': "It's up to you which platform and environment you use for the course.\n\nGitHub Codespaces or GCP VM are just possible options, but you can do the entire course from your laptop.",
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/024_070766ca79_environment-do-we-really-have-to-use-github-codesp.md'},
 {'id': 'ef96ec09e6',
  'question': 'Environment - Do I need both GitHub Codespaces and GCP?',
  'sort_order': 25,
  'content': 'Choose the approach that aligns the most with your idea for the end project.\n\nOne should suffice; however, BigQuery, which is part of GCP, will be used, so learning that is probably a better option. Alternatively, you can set up a local environment for most of this course.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/025_ef96ec09e6_environment-do-i-need-both-github-codespaces-and-g.md'},
 {'id': 'b92da7c113',
  'question': 'Environment - Could not establish connection to "MyServerName": Got bad result from install script',
  'sort_order': 26,
  'content': 'This issue occurs when attempting to connect to a GCP VM using VSCode on a Windows machine. You can resolve it by changing a registry value in the registry editor.\n\nOpen the Run command window:\n- Use the shortcut keys `Windows + R`, or\n- Right-click "Start" and click "Run".\n\nOpen the Registry Editor:\n- Type `regedit` in the Run command window, then press Enter.\n\nChange the registry value:\n- Navigate to `HKEY_CURRENT_USER\\Software\\Microsoft\\Command Processor`.\n- Change the "Autorun" value from "if exists" to a blank.\n\nAlternatively, you can delete the saved fingerprint within the known_hosts file:\n\nIn Windows, locate the file at `C:\\Users\\<your_user_name>\\.ssh\\known_hosts` and remove the entry for the server.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/026_b92da7c113_environment-could-not-establish-connection-to-myse.md'},
 {'id': 'a8219681ec',
  'question': 'Environment - Why are we using GCP and not other cloud providers?',
  'sort_order': 27,
  'content': 'For uniformity.\n\nYou can use other cloud platforms since you get every service provided by GCP in Azure and AWS. You’re not restricted to GCP and can use other platforms like AWS if you’re more comfortable.\n\nBecause everyone usually has a Google account, GCP offers a free trial period with $300 in credits for new users. Additionally, we are working with BigQuery, which is part of GCP.\n\nNote that to sign up for a free GCP account, you must have a valid credit card.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/027_a8219681ec_environment-why-are-we-using-gcp-and-not-other-clo.md'},
 {'id': 'e7738f47c8',
  'question': 'Should I pay for cloud services?',
  'sort_order': 28,
  'content': "It's not mandatory. You can take advantage of their free trial.",
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/028_e7738f47c8_should-i-pay-for-cloud-services.md'},
 {'id': '77a076baa3',
  'question': 'Environment: The GCP and other cloud providers are unavailable in some countries. Is it possible to provide a guide to installing a home lab?',
  'sort_order': 29,
  'content': 'You can do most of the course without a cloud. Almost everything we use (excluding BigQuery) can be run locally. We won’t be able to provide guidelines for some things, but most of the materials are runnable without GCP.\n\nFor everything in the course, there’s a local alternative. You could even do the whole course locally. Note that Homework 3 requires BigQuery.',
  'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/029_77a076baa3_environment-the-gcp-and-other-cloud-providers-are.md'},
 {'id': '109e36c115',
  'question': 'Environment: Is GCP Sandbox enough or we need the Free Trial?',
  'sort_order': 30,

This is text search, also known as "lexical search". We look for exact matches between our query and the documents.

### 2. Vector search

Text search has limitations. Consider these two queries:
* "I just discovered the program, can I still enroll?"
* "I just found out about the course, can I still join?"

These ask the same question but share no common words (among important ones). Text search would fail to find relevant matches.
This is where embeddings help. Embeddings are numerical representations of text that capture semantic meaning. Words and phrases with similar meanings have similar embeddings, even if they use different words.

Vector search uses these embeddings to identify semantically similar documents, rather than just exact word matches.
For vector search, we need to turn our documents into vectors (embeddings).
We will use the sentence-transformers library for this purpose.

In [52]:
from sentence_transformers import SentenceTransformer
embedding_model = SentenceTransformer('multi-qa-distilbert-cos-v1')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/523 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/265M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/333 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

The multi-qa-distilbert-cos-v1 model is trained explicitly for question-answering tasks. It creates embeddings optimized for finding answers to questions.

Other popular models include:
* all-MiniLM-L6-v2 - General-purpose, fast, and efficient
* all-mpnet-base-v2 - Higher quality, slower

In [53]:
record = de_dtc_faq[2]
text = record['question'] + ' ' + record['content']
v_doc = embedding_model.encode(text)

We combine the question and answer text, then convert it to an embedding vector.

In [54]:
query = 'I just found out about the course. Can I enroll now?'
v_query = embedding_model.encode(query)

This is how we compute similarity between the query and document vectors:

In [55]:
similarity = v_query.dot(v_doc)

The dot product measures similarity between vectors.

Values closer to 1 indicate higher similarity, closer to 0 means lower similarity. This works because the model creates normalized embeddings where cosine similarity equals the dot product.

So we can create embeddings for all documents, then compute similarity between the query and each document to find the most similar ones.
This is what VectorSearch from minsearch does. Let's use it.

First, we turn our docs into embeddings. This process takes time, so we'll monitor progress with tqdm:

In [57]:
#from tqdm.auto import tqdm
import numpy as np

faq_embeddings = []

for d in tqdm(de_dtc_faq):
    text = d['question'] + ' ' + d['content']
    v = embedding_model.encode(text)
    faq_embeddings.append(v)

faq_embeddings = np.array(faq_embeddings)

  0%|          | 0/498 [00:00<?, ?it/s]

We combine question and answer text for each FAQ entry. We convert the list to a NumPy array for efficient similarity computations.

Now let's use VectorSearch:

In [58]:
from minsearch import VectorSearch

faq_vindex = VectorSearch()
faq_vindex.fit(faq_embeddings, de_dtc_faq)

This creates a vector search index using our embeddings and original documents.

In [59]:
query = 'Can I join the course now?'
q = embedding_model.encode(query)
results = faq_vindex.search(q)

We first create an embedding for our query (q), then search for similar document embeddings.
You can easily do the same with the Evidently docs (but only use the chunk field for embeddings):

In [60]:
code_ins_embeddings = []

for d in tqdm(code_inst_chunks):
    v = embedding_model.encode(d['filename'])
    code_ins_embeddings.append(v)

code_ins_embeddings = np.array(code_ins_embeddings)

evidently_vindex = VectorSearch()
evidently_vindex.fit(code_ins_embeddings, code_inst_chunks)

  0%|          | 0/45 [00:00<?, ?it/s]

### 3. Hybrid search
Text search is fast and efficient. It works well for exact matches and specific terms, and requires no model inference. However, it misses semantically similar but differently worded queries and struggles to handle synonyms effectively.

Vector search captures semantic meaning and handles paraphrased questions. It works with synonyms and related concepts. But it may miss exact keyword matches.
Combining both approaches gives us the best of both worlds. This is known as "hybrid search."
The code is quite simple:

In [61]:
query = 'Can I join the course now?'

text_results = faq_index.search(query, num_results=5)

q = embedding_model.encode(query)
vector_results = faq_vindex.search(q, num_results=5)

final_results = text_results + vector_results

### 4. Putting this together
Our search is implemented!
But before we can use it in our agent, we need to organize the code. Let's put all the code into different functions:

def text_search(query):
    return faq_index.search(query, num_results=5)

def vector_search(query):
    q = embedding_model.encode(query)
    return faq_vindex.search(q, num_results=5)

def hybrid_search(query):
    text_results = text_search(query)
    vector_results = vector_search(query)
    
    # Combine and deduplicate results
    seen_ids = set()
    combined_results = []

    for result in text_results + vector_results:
        if result['filename'] not in seen_ids:
            seen_ids.add(result['filename'])
            combined_results.append(result)
    
    return combined_results

### 5. Selecting the best approach

Much like with chunking, you should always start with the simplest approach. For search, that's text search. It's faster, easier to debug, and works well for many use cases. Only add complexity when a simple text search isn't sufficient.

## Day 4: Agents and Tools

So far, we have done:
* Day 1: Downloaded the data from a GitHub repository
* Day 2: Processed it by chunking it where necessary
* Day 3: Indexed the data so it's searchable

Note that it took us quite a lot of time. This is not a coincidence. Data preparation is the most time-consuming and critical part of building AI agents. Without properly prepared, cleaned, and indexed data, even the most sophisticated agent will provide poor results.
Now it's time to create an AI agent that will use this data through the search engine that we created before.
This allows us to build context-aware agents. They can provide accurate, relevant answers based on your specific domain knowledge rather than just general training data.

In particular, we will:
* Learn what makes an AI system "agentic" through tool use
* Build an agent that can use the search function
* Use Pydantic AI to make it easier to implement agents

### 1. Tools and Agents

I have the impression that everyone has their own definition for an AI agent. But here is a simple one: an agent is an LLM that can not only generate texts, but also invoke tools. Tools are external functions that the LLM can call in order to retrieve information, perform calculations, or take actions.
In our case, the agent needs to answer our questions using the content of the GitHub repository. So, the tool (only one) is a search(query).
But first, let's consider a situation where we have no tools at all. This is not an agent, it's just an LLM that can generate texts. Access to tools is what makes agents "agentic".

Let's see the difference with an example.
We will try asking a question without giving the LLM access to search:

In [62]:
# I will modify this code as well to work woth hugging face mistral (since my openai quota is so low)
# No import openai needed as we are using the custom llm function
# No openai_client needed

user_prompt = "I just discovered the course, can I join now?"

# chat_messages is not directly used by the custom llm function,
# as the llm function constructs its own messages list internally.
# We will pass the user_prompt directly to the llm function.

response = llm(user_prompt) # Call the pre-defined llm function with the user_prompt

print(response) # The llm function directly returns the generated text

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Absolutely! Our courses have rolling enrollment, which means you can join at any time. Once you've signed up, you'll have access to all the course materials and can begin learning at your own pace. If you have any questions or need assistance getting started, please don't hesitate to contact us. We're here to help!

To get started, simply visit our website and select the course you're interested in. From there, you'll be able to sign up and make your payment. Once you've completed the registration process, you'll receive an email with instructions on how to access the course materials.

If you have any questions or need further assistance, please don't hesitate to contact us using the information provided on our website. We're here to help you every step of the way!

The response is generic. In our case, it's this:

“It depends on the course you're interested in. Many courses allow late enrollment, while others might have specific deadlines. I recommend checking the course's official website or contacting the instructor or administration for more details on joining.”

This answer is not really useful.

But if we let it invoke the search(query), the agent can give us a more useful answer.

Here's how the conversation would flow with our agent using the search tool:
* User: "I just discovered the course, can I join now?"
* Agent thinking: I can't answer this question, so I need to search for information about course enrollment and timing.
* Tool call: search("course enrollment join registration deadline")
* Tool response: (...search results...)
* Agent response: "Yes, you can still join the course even after the start date..."

We will now explore how to implement it with OpenAI.

### 2. Function Calling with OpenAI (or with another LLM)

One problem that we are facing now is that we have chosen to use mistral 7b model from Hugging Face but it doesn't support tool calling. The only way we can use it in our context is like below:

In [65]:
system_prompt = """
You are a helpful assistant for a course.
"""

question = "I just discovered the course, can I join now?"

# The llm function (Mistral 7B) is a simple text generation function
# and does not support the 'tools' argument or structured tool-call responses.
# It also does not directly process a separate 'system_prompt' in the same way.
# It expects a single prompt string as input.

response = llm(question)

# The 'response' object will now be a string, not an object with '.output' or tool calls.
# Subsequent cells in this section that expect tool call information will fail.

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

The 'response' object will now be a string, not an object with '.output' or tool calls.

Subsequent cells in this section that expect tool call information will fail.

### Can we trick Mistral 7b to use Tool-like functions?

Let's fool around to see if we can simulate it via prompting: instruct the model to output JSON when it wants to call a tool, then parse that output yourself.

In [5]:
# Define your tools as a description the model can understand
tools_description = """
You have access to the following tools:
- text_search(query: str): Searches the course documentation for relevant information.

When you need to use a tool, respond ONLY with a JSON object like:
{"tool_call": {"name": "text_search", "arguments": {"query": "your search query"}}}

When you have enough information to answer, respond normally in plain text.
"""

system_prompt = f"""You are a helpful assistant for a course.
{tools_description}
"""

def build_prompt(system, messages):
    """Combine system prompt + chat history into a single prompt for Mistral."""
    full_messages = [{"role": "system", "content": system}] + messages
    return generator.tokenizer.apply_chat_template(
        full_messages, tokenize=False, add_generation_prompt=True
    )

# Simulated response object to mimic OpenAI's structure
class ToolCall:
    def __init__(self, name, arguments):
        self.name = name
        self.arguments = arguments  # dict

class Message:
    def __init__(self, content, tool_call=None):
        self.content = content
        self.tool_call = tool_call  # ToolCall or None

class Response:
    def __init__(self, message):
        self.output = [message]

def parse_response(raw_text):
    """Parse raw model output into a Response object."""
    raw_text = raw_text.strip()
    # Try to detect a tool call in the output
    json_match = re.search(r'\{.*"tool_call".*\}', raw_text, re.DOTALL)
    if json_match:
        try:
            parsed = json.loads(json_match.group())
            tc = parsed["tool_call"]
            tool_call = ToolCall(name=tc["name"], arguments=tc["arguments"])
            return Response(Message(content=None, tool_call=tool_call))
        except (json.JSONDecodeError, KeyError):
            pass
    # Plain text response
    return Response(Message(content=raw_text))

def llm_with_tools(messages, system_prompt):
    prompt = build_prompt(system_prompt, messages)
    outputs = generator(
        prompt,
        max_new_tokens=200,
        do_sample=True,
        temperature=0.7,
        top_k=50,
        top_p=0.95,
        truncation=True
    )
    raw = outputs[0]["generated_text"].replace(prompt, "").strip()
    return parse_response(raw)

In [72]:
# now our agentic loop looks like this:
def run_agent(question, system_prompt, tools: dict):
    messages = [{"role": "user", "content": question}]

    while True:
        response = llm_with_tools(messages, system_prompt)
        message = response.output[0]

        if message.tool_call:
            # Execute the tool
            tool_name = message.tool_call.name
            tool_args = message.tool_call.arguments
            print(f"Calling tool: {tool_name} with args: {tool_args}")

            tool_result = tools[tool_name](**tool_args)

            # Feed result back into context
            messages.append({"role": "assistant", "content": f'[Tool call: {tool_name}({tool_args})]'}) # Corrected line
            messages.append({"role": "user", "content": f"Tool result: {tool_result}"})
        else:
            # Final answer
            return message.content

# Example usage
# Make sure the 'text_search' function is defined before this cell is run.
# The 'text_search_tool' variable is a *description* of the tool, not the tool itself.
# We need to pass the actual callable function 'text_search'.
result = run_agent(
    question="I just discovered the course, can I join now?",
    system_prompt=system_prompt,
    tools={"text_search": text_search} # Changed text_search_tool to text_search
)
print(result)

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Calling tool: text_search with args: {'query': 'course registration'}
To join the course, you should register before it starts using this [link](https://airtable.com/shr6oVXeQvSI5HuWD). You do not need prior data engineering experience but should have basic coding experience and familiarity with SQL. If you have experience with Python, it is helpful but not required. You can also join the course Telegram channel for announcements. You can start preparing by installing the dependencies and requirements listed in the course FAQ. If you miss the registration deadline, you can still follow the course materials and submit the homework, but be aware of the deadlines for turning in assignments.

In [75]:
#result is still a string
result

'To join the course, you should register before it starts using this [link](https://airtable.com/shr6oVXeQvSI5HuWD). You do not need prior data engineering experience but should have basic coding experience and familiarity with SQL. If you have experience with Python, it is helpful but not required. You can also join the course Telegram channel for announcements. You can start preparing by installing the dependencies and requirements listed in the course FAQ. If you miss the registration deadline, you can still follow the course materials and submit the homework, but be aware of the deadlines for turning in assignments.'

### Tool calling with a model that can call tools:

Let's create an agent now. In OpenAI's terminology, we'll need to use "function calling".
We will begin with our FAQ example and text search. You can easily extend it to vector or hybrid search or change it to the Evidently docs.
This is the function we implemented previously:

In [ ]:
!pip install mistralai

In [12]:
# below is what is used for openai but a function wrapper is missing in order to use it with mistral
text_search_tool_openai = {
    "type": "function",
    "name": "text_search",
    "description": "Search the FAQ database",
    "parameters": {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": "Search query text to look up in the course FAQ."
            }
        },
        "required": ["query"],
        "additionalProperties": False
    }
}
# To use with mistral:
text_search_tool = [
    {
        "type": "function",
        "function": {          # <-- this "function" wrapper is what was missing
            "name": "text_search",
            "description": "Search the FAQ database",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "Search query text to look up in the course FAQ."
                    }
                },
                "required": ["query"]
            }
        }
    }
]

In [11]:
def text_search(query):
    return faq_index.search(query, num_results=5)

In [14]:
messages = [
    {
        "role": "system",
        "content": "You are a helpful assistant for a course."
    }
]

In [17]:
messages.append({"role": "user", "content": "I just discovered the course, can I join now?"})

In [20]:
messages

[{'role': 'system', 'content': 'You are a helpful assistant for a course.'},
 {'role': 'user', 'content': 'I just discovered the course, can I join now?'}]

In [24]:
from mistralai.client import Mistral
from google.colab import userdata

client = Mistral(api_key=userdata.get('mistral'))

model="mistral-small-latest"  # free tier

response = client.chat.complete(
    model = model, # The model we want to use
    messages = messages, # The message history, in this example we have a system (optional) + user query.
    tools = text_search_tool # The tools specifications
)

We can't just pass this function to the LLM. First, we need to describe this function, so the LLM understands how to use it.
This is done using a special description format:

This description tells the LLM:
* The function is called text_search
* It searches the FAQ database
* It takes one required parameter: query (a string)

The query should be the search text to look up in the course FAQ

Now we can use it:

In [28]:
response

ChatCompletionResponse(id='dee62c51f5f840e995183d9facd747de', object='chat.completion', model='mistral-small-latest', usage=UsageInfo(prompt_tokens=110, completion_tokens=20, total_tokens=130, prompt_audio_seconds=Unset(), prompt_tokens_details={'cached_tokens': 0}), created=1775128137, choices=[ChatCompletionChoice(index=0, message=AssistantMessage(role='assistant', content='', tool_calls=[ToolCall(function=FunctionCall(name='text_search', arguments='{"query": "Can I join the course after it has started?"}'), id='EXePt0c6n', type=None, index=0)], prefix=False), finish_reason='tool_calls')])

Nice! The response is no longer a string but an object :)
More precisely a ChatCompletionResponse object

In [32]:
response.object

'chat.completion'

But the object's attributes are quite different from how the openai version of it is mapped. The key differences vs OpenAI:

* The tool result message uses "role": "tool" instead of "type": "function_call_output"
* call_id → tool_call.id
* arguments → tool_call.function.arguments

The agent analyzed the user's question and determined that to answer it, it needs to invoke the text_search function with the arguments {"query":"join course"}.
Let's invoke the function with these arguments:

In [ ]:
#openai version (running this cell will give an error because the mapping is different from mistral's)
#call = response.output[0]

#arguments = json.loads(call.arguments)
#result = text_search(**arguments)

#call_output = {
#    "type": "function_call_output",
#    "call_id": call.call_id,
#    "output": json.dumps(result),
#}

#chat_messages.append(call)
#chat_messages.append(call_output)

#response = openai_client.responses.create(
#    model='gpt-4o-mini',
#    input=chat_messages,
#    tools=[text_search_tool]
#)

#print(response.output_text)

In [47]:
import json
# Get the tool call from Mistral's response
tool_call = response.choices[0].message.tool_calls[0]

# Parse arguments
arguments = json.loads(tool_call.function.arguments)

# Execute the tool
result = text_search(**arguments)

# Build the tool result message (Mistral format)
call_output = {
    "role": "tool",
    "tool_call_id": tool_call.id,
    "content": json.dumps(result),
}

In [48]:
# Then to continue the conversation, append both the assistant's message and the tool result back into your messages list:
messages.append(response.choices[0].message)  # assistant's tool_call message
messages.append(call_output)                   # tool result

# Make a second call to get the final answer
final_response = client.chat.complete(
    model=model,
    messages=messages,
    tools=text_search_tool
)
print(final_response.choices[0].message.content)

Yes, you can still join the course even after the start date! You are eligible to submit homework and participate. Just be mindful of the deadlines for turning in homework and the final project. You can register using this [link](https://airtable.com/shr6oVXeQvSI5HuWD) and join the [course Telegram channel](https://t.me/dezoomcamp) for announcements.

Here's what's happening:

* The LLM decided to execute a function and let us know about it
* We executed the function and saved the results
* Now we need to pass this information back to the LLM

We do it by extending the chat_messages list and sending the entire conversation history back to the LLM:

LLMs are stateless. When we make one call to the OpenAI API and then shortly afterwards make another, it doesn't know anything about the first call. So if we only send it call_output, it would have no idea how to respond to it.

This is why we need to send it the entire conversation history. It needs to know everything that happened so far:

* The system prompt (so it knows what the initial instructions are) - system_prompt
* The user prompt (so it knows what task it needs to perform) - question
* The decision to invoke the text_search tool (so it knows what function was called) - that's our call
* The output of the function (so it knows what the function returned) - that's our call_output

After we invoke it, we get back the response:
“Yes, you can still join the course even after the start date. While you won't be able to officially register, you are eligible to submit your homework. Just keep in mind that there are deadlines for submitting assignments and final projects, so it's best not to leave everything to the last minute.”
This is a useful response that we were hoping to get.

### 3. System Prompt: Instructions
Let's take another look at the code we wrote previously:

In [13]:
chat_messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user", "content": question}
]

model="mistral-small-latest"  # free tier

response = client.chat.complete(
    model = model,
    messages = chat_messages,
    tools = text_search_tool
)

We have two things here:
* system_prompt contains instructions for the LLM
* question ("user prompt") is the actual question or task

The system prompt is very important: it influences how the agent behaves. This is how we can control what the agent does and how it responds to user questions.
Usually, the more complete the instructions in the system prompt are, the better the results.
So we can extend it:

In [14]:
system_prompt = """
You are a helpful assistant for a course.

Use the search tool to find relevant information from the course materials before answering questions.

If you can find specific information through search, use it to provide accurate answers.
If the search doesn't return relevant results, let the user know and provide general guidance.
"""

When working with agents, the system prompt becomes one of the most essential variables we can adjust to influence our agent.
For example, if we want the agent to make multiple search queries, we can modify the prompt:

In [15]:
system_prompt = """
You are a helpful assistant for a course.

Always search for relevant information before answering.
If the first search doesn't give you enough information, try different search terms.

Make multiple searches if needed to provide comprehensive answers.
"""

### 4. Pydantic AI

Dealing with function calls can be cumbersome. We first need to understand which function we need to invoke. Then we need to pass the results back to the LLM and perform other tasks. It's easy to make a mistake there.

That's why we'll use a library to handle it. There are many agentic libraries: OpenAI Agents SDK, Langchain, Pydantic AI, and many more. For educational purposes, I also implemented an agents library. It's called ToyAIKit. We won't use it here, but I often use it in my lessons.
Today, we will use Pydantic AI. I like its API; it's simpler than other libraries and has good documentation.

For Pydantic AI (and for other agents libraries), we don't need to describe the function in the JSON format like we did with the plain OpenAI API. The libraries take care of it.
But we do need to add docstrings and type hints to our function. I asked ChatGPT to do it:

In [16]:
from typing import List, Any

def text_search(query: str) -> List[Any]:
    """
    Perform a text-based search on the FAQ index.

    Args:
        query (str): The search query string.

    Returns:
        List[Any]: A list of up to 5 search results returned by the FAQ index.
    """
    return faq_index.search(query, num_results=5)

We can now define an agent with Pydantic AI and give it the text_search tool:

In [ ]:
!pip install pydantic-ai

In [22]:
# luck has it : Pydantic has built-in mistral support
from pydantic_ai import Agent
from pydantic_ai.models.mistral import MistralModel
from pydantic_ai.providers.mistral import MistralProvider
from google.colab import userdata

mistral_provider = MistralProvider(api_key=userdata.get('mistral'))

mistral_model = MistralModel(
    model_name="mistral-small-latest",
    provider=mistral_provider #MistralModel from pydantic-ai doesn't directly take an api_key argument, replaced it with this
)

agent = Agent(
    name="faq_agent",
    instructions=system_prompt,
    tools=[text_search],
    model=mistral_model
)

We don't need to do anything with our text_search function. We just pass it directly to the agent.
Let's run it:

In [31]:
question = "I just discovered the course, can I join now?"

result = await agent.run(user_prompt=question)

We use await because Pydantic AI is asynchronous. If you're not running in Jupyter, you need to use asyncio.run():

In [ ]:
#import asyncio

#result = asyncio.run(agent.run(user_prompt=question))

The output:

“Yes, you can still join the course even after the start date. Although you may not officially register, you are eligible to submit your homework. Just keep in mind that there are deadlines for turning in homework and final projects, so it's advisable not to delay everything until the last minute.”

We can also look inside the result to get a detailed breakdown of the agent's reasoning and actions:

In [32]:
result.new_messages()

[ModelRequest(parts=[UserPromptPart(content='I just discovered the course, can I join now?', timestamp=datetime.datetime(2026, 4, 2, 11, 49, 37, 605605, tzinfo=datetime.timezone.utc))], timestamp=datetime.datetime(2026, 4, 2, 11, 49, 37, 605957, tzinfo=datetime.timezone.utc), instructions="You are a helpful assistant for a course.\n\nAlways search for relevant information before answering.\nIf the first search doesn't give you enough information, try different search terms.\n\nMake multiple searches if needed to provide comprehensive answers.", run_id='019d4e07-0ac4-737d-9308-46d4d88f913b'),
 ModelResponse(parts=[ToolCallPart(tool_name='text_search', args='{"query": "Can I join the course after it has started?"}', tool_call_id='HMYKzNgBW')], usage=RequestUsage(input_tokens=191, output_tokens=20), model_name='mistral-small-latest', timestamp=datetime.datetime(2026, 4, 2, 11, 49, 39, 357072, tzinfo=datetime.timezone.utc), provider_name='mistral', provider_url='https://api.mistral.ai', provider_details={'finish_reason': 'tool_calls', 'timestamp': datetime.datetime(2026, 4, 2, 11, 49, 37, tzinfo=TzInfo(0))}, provider_response_id='52aa490363114d77b847a878b01fca19', finish_reason='tool_call', run_id='019d4e07-0ac4-737d-9308-46d4d88f913b'),
 ModelRequest(parts=[ToolReturnPart(tool_name='text_search', content=[{'id': '068529125b', 'question': 'Course - Can I follow the course after it finishes?', 'sort_order': 8, 'content': 'Yes, we will keep all the materials available, so you can follow the course at your own pace after it finishes.\n\nYou can also continue reviewing the homeworks and prepare for the next cohort. You can also start working on your final capstone project.', 'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/008_068529125b_course-can-i-follow-the-course-after-it-finishes.md'}, {'id': '3f1424af17', 'question': 'Course: Can I still join the course after the start date?', 'sort_order': 3, 'content': "Yes, even if you don't register, you're still eligible to submit the homework.\n\nBe aware, however, that there will be deadlines for turning in homeworks and the final projects. So don't leave everything for the last minute.", 'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/003_3f1424af17_course-can-i-still-join-the-course-after-the-start.md'}, {'id': '9e508f2212', 'question': 'Course: When does the course start?', 'sort_order': 1, 'content': "The next cohort starts January 12th, 2026. More info at [DTC](https://datatalks.club/blog/guide-to-free-online-courses-at-datatalks-club.html).\n\n- Register before the course starts using this [link](https://airtable.com/shr6oVXeQvSI5HuWD).\n- Join the [course Telegram channel with announcements](https://t.me/dezoomcamp).\n- Don’t forget to register in DataTalks.Club's Slack and [join](https://datatalks.club/docs/general/slack/) the channel.", 'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/001_9e508f2212_course-when-does-the-course-start.md'}, {'id': '33fc260cd8', 'question': 'Course: What can I do before the course starts?', 'sort_order': 5, 'content': 'Start by installing and setting up all the dependencies and requirements:\n\n- Google Cloud account\n- Google Cloud SDK\n- Python 3 (installed with Anaconda)\n- Terraform\n- Git\n\nLook over the prerequisites and syllabus to see if you are comfortable with these subjects.', 'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/005_33fc260cd8_course-what-can-i-do-before-the-course-starts.md'}, {'id': '721f9e0c29', 'question': 'How can we contribute to the course?', 'sort_order': 35, 'content': '- [Star the repository](https://github.com/DataTalksClub/data-engineering-zoomcamp).\n- Share it with friends if you find it useful.\n- Create a pull request (PR) if you can improve the text or structure of the repository.\n- [Update this FAQ](https://github.com/DataTalksClub/faq/).', 'filename': 'faq-main/_questions/data-engineering-zoomcamp/general/035_721f9e0c29_how-can-we-contribute-to-the-course.md'}], tool_call_id='HMYKzNgBW', timestamp=datetime.datetime(2026, 4, 2, 11, 49, 39, 362242, tzinfo=datetime.timezone.utc))], timestamp=datetime.datetime(2026, 4, 2, 11, 49, 39, 362803, tzinfo=datetime.timezone.utc), instructions="You are a helpful assistant for a course.\n\nAlways search for relevant information before answering.\nIf the first search doesn't give you enough information, try different search terms.\n\nMake multiple searches if needed to provide comprehensive answers.", run_id='019d4e07-0ac4-737d-9308-46d4d88f913b'),
 ModelResponse(parts=[TextPart(content='Yes, you can still join the course even after the start date. You are eligible to submit homework and participate, but be aware that there are deadlines for assignments and the final project, so plan accordingly.')], usage=RequestUsage(input_tokens=977, output_tokens=54), model_name='mistral-small-latest', timestamp=datetime.datetime(2026, 4, 2, 11, 49, 40, 226050, tzinfo=datetime.timezone.utc), provider_name='mistral', provider_url='https://api.mistral.ai', provider_details={'finish_reason': 'stop', 'timestamp': datetime.datetime(2026, 4, 2, 11, 49, 39, tzinfo=TzInfo(0))}, provider_response_id='a3b950d8479341bd9c625a183944f53c', finish_reason='stop', run_id='019d4e07-0ac4-737d-9308-46d4d88f913b')]

It contains four items:
* ModelRequest: Represents a request sent to the model. It includes the user's prompt (UserPromptPart) and the agent's instructions.
* ModelResponse: The model's reply. We see a ToolCallPart with the decision to invoke text_search.
* ModelRequest: Contains ToolReturnPart - the results returned by the tool (search results from the FAQ index).
* ModelResponse: The final answer generated by the model in TextPart.

Pydantic AI and other frameworks handle all the complexity of function calling for us. We don't need to manually parse responses, handle tool calls, or manage conversation history. This makes our code cleaner and less error-prone.

We implemented an agent. Great! But how good is it? Is the prompt we came up good? What's better for our agent, text search, vector search or hybrid?

## Day 5: Evaluation

Is our agent actually good? Today we will see how to answer this question.

In particular, we will cover:
* Build a logging system to track agent interactions
* Create automated evaluation using AI as a judge
* Generate test data automatically
* Measure agent performance with metrics

At the end of this lesson, you'll have a thoroughly tested agent with performance metrics.
In this lesson, we'll use the FAQ database with text search, but it's applicable for any other use case.
This is going to be a long lesson, but an important one. Evaluation is critical for building reliable AI systems. Without proper evaluation, you can't tell if your changes improve or hurt performance. You can't compare different approaches. And you can't build confidence before deploying to users.

So let's start!

### Logging

The easiest thing we can do to evaluate an agent is interact with it. We ask something and look at the response. Does it make sense? For most cases, it should.
This approach is called "vibe check" - we interact with it, and if we like the results, we go ahead and deploy it.
If we don't like something, we go back and change things:
* Maybe our chunking method is not suitable? Maybe we need to have a bigger window size?
* Is our system prompt good? Maybe we need more precise instructions?
* Or we want to change something else

And we iterate.

It might be okay for the first MVP, but how can we make sure the result at the end is actually good?
We need systematic evaluation. Manual testing doesn't scale - you can't manually test every possible input and scenario. With systematic evaluation, we can test hundreds or thousands of cases automatically.
We also need to base our decisions on data. It will help us to
* Compare different approaches
* Track improvements
* Identify edge cases

We can start collecting this data ourselves: start with vibe checking, but be smart about it. We don't just test it, but also record the results.

Here's what we want to record:

* The system prompt that we used
* The model
* The user query
* The tools we use
* The responses and the back-and-forth interactions between the LLM and our tools
* The final response

To make it simpler, we'll implement a simple logging system ourselves: we will just write logs to json files.

You shouldn't use it in production. In practice, you will want to send these logs to some log collection system, or use specialized LLM evaluation tools like Evidently, LangWatch or Arize Phoenix.

Let's extract all this information from the agent and from the run results:

In [33]:
from pydantic_ai.messages import ModelMessagesTypeAdapter


def log_entry(agent, messages, source="user"):
    tools = []

    for ts in agent.toolsets:
        tools.extend(ts.tools.keys())

    dict_messages = ModelMessagesTypeAdapter.dump_python(messages)

    return {
        "agent_name": agent.name,
        "system_prompt": agent._instructions,
        "provider": agent.model.system,
        "model": agent.model.model_name,
        "tools": tools,
        "messages": dict_messages,
        "source": source
    }

This code extracts the key information from our agent:

* the configuration (name, prompt, model)
* available tools
* complete message history (user input, tool calls, responses)

We also use ModelMessagesTypeAdapter.dump_python(messages) to convert internal message format into regular Python dictionaries. This makes it easier to save it to JSON and process later.

We also add the source parameter. It tracks where the question came from. We start with "user" but later we'll use AI-generated queries. Sometimes it may be important to tell them apart for analysis.
This code is generic so it will work with any Pydantic AI agent. If you use a different library, you'll need to adjust this code.

Let's write these logs to a folder:

In [52]:
import json
import secrets
from pathlib import Path
from datetime import datetime


LOG_DIR = Path('logs')
LOG_DIR.mkdir(exist_ok=True)


def serializer(obj):
    if isinstance(obj, datetime):
        return obj.isoformat()
    raise TypeError(f"Type {type(obj)} not serializable")


def log_interaction_to_file(agent, messages, source='user'):
    entry = log_entry(agent, messages, source)

    # Get the raw timestamp. It might be a datetime object or an ISO string.
    raw_timestamp = entry['messages'][-1]['timestamp']

    if isinstance(raw_timestamp, str):
        # If it's a string, convert it to datetime object
        ts_obj = datetime.fromisoformat(raw_timestamp.replace("Z", "+00:00"))
    elif isinstance(raw_timestamp, datetime):
        # If it's already a datetime object, use it directly
        ts_obj = raw_timestamp
    else:
        raise TypeError(f"Unexpected type for timestamp: {type(raw_timestamp)}")

    # Now format the datetime object to the desired string
    ts_str = ts_obj.strftime("%Y%m%d_%H%M%S")
    rand_hex = secrets.token_hex(3)

    filename = f"{agent.name}_{ts_str}_{rand_hex}.json"
    filepath = LOG_DIR / filename

    with filepath.open("w", encoding="utf-8") as f_out:
        json.dump(entry, f_out, indent=2, default=serializer)

    return filepath

This creates a simple interactive loop where:

* User enters a question
* Agent processes it and responds
* Complete interaction is logged to a file

Try these questions:
* how do I use docker on windows?
* can I join late and get a certificate?
* what do I need to do for the certificate?

### Adding References

When interacting with the agent, I noticed one thing: it doesn't include the reference to the original documents.
Let's fix it by adjusting the prompt:

In [35]:
system_prompt = """
You are a helpful assistant for a course.

Use the search tool to find relevant information from the course materials before answering questions.

If you can find specific information through search, use it to provide accurate answers.

Always include references by citing the filename of the source material you used.
When citing the reference, replace "faq-main" by the full path to the GitHub repository: "https://github.com/DataTalksClub/faq/blob/main/"
Format: [LINK TITLE](FULL_GITHUB_LINK)

If the search doesn't return relevant results, let the user know and provide general guidance.
""".strip()

# Create another version of agent, let's call it faq_agent_v2
agent = Agent(
    name="faq_agent_v2",
    instructions=system_prompt,
    tools=[text_search],
    model=mistral_model
)

This is the output I now get for the question "can I join late and get a certificate?":

Yes, you can join the course late and still be eligible for a certificate, as long as you complete the required peer-reviewed capstone projects on time. You do not need to complete the homework assignments if you join late, which allows for flexibility in participation.

However, please note that certificates are only awarded to those who finish the course with a “live” cohort; they are not available for those who choose the self-paced mode. This is because peer-reviewing capstone projects is a requirement that can only be done while the course is active.

For more details, you can refer to the following resources:
* Do I need to do the homeworks to get the certificate?
* Can I follow the course in a self-paced mode and get a certificate?
* Can I still join the course after the start date?

Note that I added this to the prompt:

When citing the reference, replace "faq-main" by the full path to the GitHub repository: "https://github.com/DataTalksClub/faq/blob/main/"

When analyzing the results, I noticed that we should have stripped "faq-main" from the filename on Day 1 when we were preparing the data. We should come back to it and adjust the ingestion process, but I won't do it here now.

We can also further adjust the instructions to make it cite the references immediately in the paragraph if we want.
Now we collect more data and finally start testing it.

### LLM as a Judge
You can ask your colleagues to also do a "vibe check", but make sure you record the data. Often collecting 10-20 examples and manually inspecting them is enough to understand how your model is doing.

Don't be afraid of putting manual work into evaluation. Manual evaluation will help you understand edge cases, learn what good responses look like and think of evaluation criteria for automated checks later.

For example, I manually inspected the output and noticed that references are missing. So we will later add it as one of the checks.
So, in our case, we can have the following checks:
* Does the agent follow the instructions?
* Given the question, does the answer make sense?
* Does it include references?
* Did the agent use the available tools?

We don't have to evaluate this manually. Instead, we can delegate this to AI. This technique is called "LLM as a Judge".
The idea is simple: we use one LLM to evaluate the outputs of another LLM. This works because LLMs are good at following detailed evaluation criteria.
Our system prompt for the judge (we'll call it "evaluation agent" because it sounds cooler) can look like that:

In [36]:
evaluation_prompt = """
Use this checklist to evaluate the quality of an AI agent's answer (<ANSWER>) to a user question (<QUESTION>).
We also include the entire log (<LOG>) for analysis.

For each item, check if the condition is met.

Checklist:

- instructions_follow: The agent followed the user's instructions (in <INSTRUCTIONS>)
- instructions_avoid: The agent avoided doing things it was told not to do
- answer_relevant: The response directly addresses the user's question
- answer_clear: The answer is clear and correct
- answer_citations: The response includes proper citations or sources when required
- completeness: The response is complete and covers all key aspects of the request
- tool_call_search: Is the search tool invoked?

Output true/false for each check and provide a short explanation for your judgment.
""".strip()

Since we expect a very well defined structure of the response, we can use structured output.
We can define a Pydantic class with the expected response structure, and the LLM will produce output that matches this schema exactly.
This is how we do it:

In [37]:
from pydantic import BaseModel

class EvaluationCheck(BaseModel):
    check_name: str
    justification: str
    check_pass: bool

class EvaluationChecklist(BaseModel):
    checklist: list[EvaluationCheck]
    summary: str

This code defines the structure we expect from our evaluation:
* Each check has a name, justification, and pass/fail result
* The overall evaluation includes a list of checks and a summary

Note that justification comes before check_pass. This makes the LLM reason about the answer before giving the final judgment, which typically leads to better evaluation quality.

With Pydantic AI in order to make the output follow the specified class, we use the parameter output_type:

In [38]:
eval_agent = Agent(
    name='eval_agent',
    model=mistral_model,
    instructions=evaluation_prompt,
    output_type=EvaluationChecklist
)

Usually it's a good idea to evaluate the results of one model (for example "gpt-4o-mini") with another model (e.g. "gpt-5-nano"). A different model can catch mistakes, reduce self-bias, and give a second opinion. This makes evaluations more reliable.

We have the instructions, and we have the agent. In order to run the agent, it needs input. We'll start with a template:

In [39]:
user_prompt_format = """
<INSTRUCTIONS>{instructions}</INSTRUCTIONS>
<QUESTION>{question}</QUESTION>
<ANSWER>{answer}</ANSWER>
<LOG>{log}</LOG>
""".strip()

We use XML markup because it's easier and more clear for LLMs to understand the input. XML tags help the model see the structure and boundaries of different sections in the prompt.

Let's fill it in. First, define a helper function for loading JSON log files:

In [40]:
def load_log_file(log_file):
    with open(log_file, 'r') as f_in:
        log_data = json.load(f_in)
        log_data['log_file'] = log_file
        return log_data

In [43]:
!touch ./logs/faq_agent_v2_20250926_072928_467470.json

In [53]:
# Run an agent interaction and log it to create a valid JSON file
question = "can I join late and get a certificate?"
result = await agent.run(user_prompt=question)
new_log_filepath = log_interaction_to_file(
    agent,
    result.new_messages(),
    source='user'
)
print(f"Generated log file: {new_log_filepath}")

Generated log file: logs/faq_agent_v2_20260402_120659_cacc5b.json

We also add the filename in the result - it'll help us with tracking later.
Now let's use it:

In [44]:
# the code below gave an error (due to the log file being absent
#so I had to create it on the cell above and modified as the cell below)
#log_record = load_log_file('./logs/faq_agent_v2_20250926_072928_467470.json')

#instructions = log_record['system_prompt']
#question = log_record['messages'][0]['parts'][0]['content']
#answer = log_record['messages'][-1]['parts'][0]['content']
#log = json.dumps(log_record['messages'])

#user_prompt = user_prompt_format.format(
#    instructions=instructions,
#    question=question,
#    answer=answer,
#    log=log
#)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [54]:
log_record = load_log_file(new_log_filepath)

instructions = log_record['system_prompt']
question = log_record['messages'][0]['parts'][0]['content']
answer = log_record['messages'][-1]['parts'][0]['content']
log = json.dumps(log_record['messages'])

user_prompt = user_prompt_format.format(
    instructions=instructions,
    question=question,
    answer=answer,
    log=log
)

The user input is ready and we can test it!

In [55]:
result = await eval_agent.run(user_prompt, output_type=EvaluationChecklist)

checklist = result.output
print(checklist.summary)

for check in checklist.checklist:
    print(check)

The AI agent's answer meets all the criteria in the checklist. It followed instructions, avoided prohibited actions, provided a relevant and clear answer, included proper citations, was complete, and used the search tool as required.
check_name='instructions_follow' justification="The agent followed the user's instructions by using the search tool to find relevant information from the course materials before answering the question." check_pass=True
check_name='instructions_avoid' justification='The agent did not violate any instructions it was told not to do.' check_pass=True
check_name='answer_relevant' justification="The response directly addresses the user's question about joining late and receiving a certificate." check_pass=True
check_name='answer_clear' justification='The answer is clear and correct, providing specific conditions for receiving a certificate when joining late.' check_pass=True
check_name='answer_citations' justification='The response includes a proper citation to the source material used, formatted as required.' check_pass=True
check_name='completeness' justification='The response is complete and covers all key aspects of the request, including the condition for receiving a certificate and the exemption from homework assignments.' check_pass=True
check_name='tool_call_search' justification='The search tool was invoked to find relevant information from the course materials.' check_pass=True

This code:
* Loads a saved interaction log
* Extracts the key components (instructions, question, answer, full log)
* Formats them into the evaluation prompt
* Runs the evaluation agent
* Prints the results

When we run it, we'll see this:
```
check_name='instructions_follow' justification='The assistant called the search tool (log shows a text_search call) but did not follow the instruction to include references (file names) from course materials; thus it did not fully follow the provided instructions.' check_pass=False
check_name='instructions_avoid' justification='No forbidden actions in the instructions were performed; the assistant did not do anything it was explicitly told to avoid.' check_pass=True
check_name='answer_relevant' justification='The response directly addressed how to install Kafka client libraries in Python and gave pip/conda commands, so it is relevant to the question.' check_pass=True
check_name='answer_clear' justification='The answer is concise and the installation commands are correct, though it omitted some caveats; overall it is clear and understandable.' check_pass=True
check_name='answer_citations' justification='The reply did not include any citations or filenames from the course materials as required by the instructions.' check_pass=False
check_name='completeness' justification='The answer omitted important details and alternatives (e.g., kafka-python library, librdkafka dependency, broker setup, and course-material citations), so it is not fully complete.' check_pass=False
check_name='tool_call_search' justification='The log shows a text_search tool call was made before the answer was given.' check_pass=True
```

Note that we're putting the entire conversation log into the prompt, which is not really necessary. We can reduce it to make it less verbose.
For example, like that:

In [56]:
def simplify_log_messages(messages):
    log_simplified = []

    for m in messages:
        parts = []

        for original_part in m['parts']:
            part = original_part.copy()
            kind = part['part_kind']

            if kind == 'user-prompt':
                del part['timestamp']
            if kind == 'tool-call':
                del part['tool_call_id']
            if kind == 'tool-return':
                del part['tool_call_id']
                del part['metadata']
                del part['timestamp']
                # Replace actual search results with placeholder to save tokens
                part['content'] = 'RETURN_RESULTS_REDACTED'
            if kind == 'text':
                del part['id']

            parts.append(part)

        message = {
            'kind': m['kind'],
            'parts': parts
        }

        log_simplified.append(message)
    return log_simplified

We make it simpler:

* remove timestamps and IDs that aren't needed for evaluation
* replace actual search results with a placeholder
* keep only the essential structure

This is helpful because it reduces the number of tokens we send to the evaluation model, which lowers the costs and speeds up evaluation.

Let's put everything together:

In [58]:
async def evaluate_log_record(eval_agent, log_record):
    messages = log_record['messages']

    instructions = log_record['system_prompt']
    question = messages[0]['parts'][0]['content']
    answer = messages[-1]['parts'][0]['content']

    log_simplified = simplify_log_messages(messages)
    log = json.dumps(log_simplified)

    user_prompt = user_prompt_format.format(
        instructions=instructions,
        question=question,
        answer=answer,
        log=log
    )

    result = await eval_agent.run(user_prompt, output_type=EvaluationChecklist)
    return result.output


log_record = load_log_file('/content/logs/faq_agent_v2_20260402_120659_cacc5b.json')
eval1 = await evaluate_log_record(eval_agent, log_record)

We know how to log our data and how to run evals on our logs.

Great. But how do we get more data to get a better understanding of the performance of our model?

### Data Generation
We can ask AI to help. What if we used it for generating more questions? Let's do that.

We can sample some records from our database. Then for each record, ask an LLM to generate a question based on the record. We use this question as input to our agent and log the answers.

Let’s start by defining the question generator:

In [60]:
question_generation_prompt = """
You are helping to create test questions for an AI agent that answers questions about a data engineering course.

Based on the provided FAQ content, generate realistic questions that students might ask.

The questions should:

- Be natural and varied in style
- Range from simple to complex
- Include both specific technical questions and general course questions

Generate one question for each record.
""".strip()

class QuestionsList(BaseModel):
    questions: list[str]

question_generator = Agent(
    name="question_generator",
    instructions=question_generation_prompt,
    model=mistral_model,
    output_type=QuestionsList
)

This prompt is designed for our specific use case (data engineering course FAQ). You should adjust it for your project.
We will send it a bunch of records, and it will generate a question from each of them.

Note: we use a simple way of generating questions. We can use a more complex approach where we also track the source (filename) of the question. If we do it, we can later check if this file was retrieved and cited in the answer. But we won't do it today to make things simpler.

Now let's sample 10 records from our dataset using Python's built-in random.sample function:

In [61]:
import random

sample = random.sample(de_dtc_faq, 10)
prompt_docs = [d['content'] for d in sample]
prompt = json.dumps(prompt_docs)

result = await question_generator.run(prompt)
questions = result.output.questions

Now we simply iterate over each of the question, ask our agent and log the results:

In [62]:
from tqdm.auto import tqdm

for q in tqdm(questions):
    print(q)

    result = await agent.run(user_prompt=q)
    print(result.output)

    log_interaction_to_file(
        agent,
        result.new_messages(),
        source='ai-generated'
    )

    print()

  0%|          | 0/10 [00:00<?, ?it/s]

I encountered an error while running `./spark-submit.sh streaming.py` in tutorial 13.2. The error message indicates that the SparkContext is stopped and all masters are unresponsive. How can I resolve this issue?
The error you encountered, where the `SparkContext` is stopped and all masters are unresponsive, is often caused by a version mismatch between your local PySpark installation and the Spark version used in the Docker environment. Here’s how you can resolve it:

---

### **Solution: Downgrade PySpark**
1. **Downgrade your local PySpark** to version **3.3.1** to match the version used in the Docker setup.
   Run the following command:
   ```bash
   pip install pyspark==3.3.1
   ```

2. **Verify the Spark version** in your Docker environment:
   - Check the `spark-master` logs to confirm the Spark version being used:
     ```bash
     docker ps
     docker exec -it <spark_master_container_id> bash
     cat logs/spark-master.out
     ```
   - Look for the Spark version in the logs (e.g., `Spark version: 3.3.1`).

3. **Ensure consistency**:
   - If the Docker setup uses a different Spark version, adjust the `SPARK_VERSION` variable in your `build.sh` file to match your local PySpark version.

---

### **Additional Troubleshooting Steps**
- **Check Spark Master Logs**:
  If the issue persists, inspect the Spark master logs for errors or warnings:
  ```bash
  docker exec -it <spark_master_container_id> bash
  cat logs/spark-master.out
  ```
  Look for timestamps matching your error to identify the root cause.

- **Restart Spark Services**:
  Sometimes, restarting the Spark master and worker containers can resolve connectivity issues:
  ```bash
  docker-compose down
  docker-compose up -d
  ```

---

### **References**
- [Python Kafka: ./spark-submit.sh streaming.py - ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.](https://github.com/DataTalksClub/faq/blob/main/_questions/data-engineering-zoomcamp/module-7/017_477104b863_python-kafka-spark-submitsh-streamingpy-error-stan.md)
- [Python Kafka: ./spark-submit.sh streaming.py - How to check why Spark master connection fails](https://github.com/DataTalksClub/faq/blob/main/_questions/data-engineering-zoomcamp/module-7/018_e7015b4263_python-kafka-spark-submitsh-streamingpy-how-to-che.md)

How can I retrieve the DDL statement for a BigQuery table to recreate its schema and data layout?
To retrieve the **DDL (Data Definition Language)** statement for a BigQuery table and recreate its schema and data layout, you can use the **`INFORMATION_SCHEMA.TABLES`** view. This method works for both **native (managed) tables** and **external tables**.

---

### **Steps to Retrieve DDL for a BigQuery Table**

#### **1. For Native (Managed) Tables**
Run the following query, replacing `your_dataset` and `your_table_name` with your dataset and table names:

```sql
SELECT table_name, ddl
FROM `your_dataset`.INFORMATION_SCHEMA.TABLES
WHERE table_name = 'your_table_name';
```

**Example:**
```sql
SELECT table_name, ddl
FROM `zoomcamp.INFORMATION_SCHEMA.TABLES`
WHERE table_name = 'yellow_tripdata_parquet';
```

This will return the `CREATE TABLE` statement required to recreate the table, including all columns, data types, and constraints.

---

#### **2. For External Tables**
The process is the same, but the DDL will include the `OPTIONS` clause specifying the external data source (e.g., format and file URIs).

**Example:**
```sql
SELECT table_name, ddl
FROM `zoomcamp.INFORMATION_SCHEMA.TABLES`
WHERE table_name = 'yellow_tripdata_parquet_ext';
```

The result will look like:
```sql
CREATE EXTERNAL TABLE `zoomcamp-ingenieria-datos.zoomcamp.yellow_tripdata_parquet_ext`
OPTIONS(
    format="PARQUET",
    uris=["gs://newyork-taxi/yellow_tripdata_*.parquet"]
);
```

---

### **Key Notes**
- This method works for both **native** and **external** tables.
- The `ddl` column in the `INFORMATION_SCHEMA.TABLES` view contains the full `CREATE TABLE` or `CREATE EXTERNAL TABLE` statement.
- For more details, refer to the [BigQuery `INFORMATION_SCHEMA.TABLES` documentation](https://cloud.google.com/bigquery/docs/information-schema-tables).

---
**Reference:**
[How to obtain the DDL of a table in BigQuery?](https://github.com/DataTalksClub/faq/blob/main/_questions/data-engineering-zoomcamp/module-3/025_7df3102580_bigquery-table-ddl-information-schema.md)

I missed the registration deadline for the course. Can I still submit the homework and final project?
Based on the available information, here's what applies to your situation:

1. **Late Homework Submissions**:
   Late submissions for homework are **not allowed**. If the submission form is still open after the due date, you *may* still submit, but it will be considered late. Always confirm your submission by checking the date-timestamp on the course page while logged in.
   [(Source)](https://github.com/DataTalksClub/faq/blob/main/_questions/data-engineering-zoomcamp/general/017_4dbd2eea47_homework-are-late-submissions-of-homework-allowed.md)

2. **Project Submissions**:
   - You have **two attempts** to submit your project.
   - If you miss the first project deadline, you can still submit during the second attempt.
   - The second attempt is also available if you fail the first submission.
   [(Source)](https://github.com/DataTalksClub/faq/blob/main/_questions/data-engineering-zoomcamp/general/039_9b0561dbf8_project-what-is-project-attempt-1-and-project-atte.md)
   [(Source)](https://github.com/DataTalksClub/faq/blob/main/_questions/data-engineering-zoomcamp/project/004_5c5321c295_project-1-project-2.md)

### Summary:
- **Homework**: Late submissions are generally not allowed, but you can submit if the form is still open (though it may be considered late).
- **Final Project**: You can submit during the second attempt if you miss the first deadline.

For exact dates and further clarification, check the [course website](https://courses.datatalks.club/de-zoomcamp-2025/) or the [Google Calendar](https://calendar.google.com/calendar/?cid=ZXIxcjA1M3ZlYjJpcXU0dTFmaG02MzVxMG9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ).
[(Source)](https://github.com/DataTalksClub/faq/blob/main/_questions/data-engineering-zoomcamp/general/016_d3f485cd10_homework-what-are-homework-and-project-deadlines.md)

I'm getting an error with my `docker-compose.yaml` file: 'service pgdatabase refers to undefined volume dtc_postgres_volume_local'. How can I fix this?
The error `'service pgdatabase refers to undefined volume dtc_postgres_volume_local'` occurs because the `docker-compose.yaml` file references a volume (`dtc_postgres_volume_local`) that hasn't been defined in the `volumes` section of the file.

### Solution:
Add the volume definition to your `docker-compose.yaml` file under the `volumes` section. Here's how you can fix it:

```yaml
volumes:
  dtc_postgres_volume_local:
```

### Example:
Your `docker-compose.yaml` should include something like this:

```yaml
services:
  pgdatabase:
    image: postgres:13
    volumes:
      - dtc_postgres_volume_local:/var/lib/postgresql/data
    # ... other configurations ...

volumes:
  dtc_postgres_volume_local:
```

### Steps:
1. Open your `docker-compose.yaml` file.
2. Add the `volumes` section at the root level (same level as `services`).
3. Define the volume `dtc_postgres_volume_local` as shown above.
4. Save the file and run `docker compose up` again.

---

### References:
- [Docker-Compose - Error undefined volume in Windows/WSL](https://github.com/DataTalksClub/faq/blob/main/_questions/data-engineering-zoomcamp/module-1/051_5f056e236c_docker-compose-error-undefined-volume-in-windowsws.md)
- [Docker-Compose: mounting error](https://github.com/DataTalksClub/faq/blob/main/_questions/data-engineering-zoomcamp/module-1/037_3f1c2f93bd_docker-compose-mounting-error.md)

How can I generate a pip-friendly `requirements.txt` file from an Anaconda environment?
To generate a pip-friendly `requirements.txt` file from an Anaconda environment, follow these steps:

1. Install `pip` in your Anaconda environment (if not already installed):
   ```bash
   conda install pip
   ```

2. Generate the `requirements.txt` file using:
   ```bash
   pip list --format=freeze > requirements.txt
   ```

**Note:**
- Using `conda list -d > requirements.txt` will **not** produce a pip-friendly file.
- While `pip freeze > requirements.txt` may work, it can sometimes include odd pathing issues.

For more details, refer to the [Anaconda to PIP FAQ](https://github.com/DataTalksClub/faq/blob/main/_questions/data-engineering-zoomcamp/module-1/133_a9081d1a79_anaconda-to-pip.md).

I'm using dbt Cloud for the course, but the interface doesn't fully match the demo. Is this expected?
Yes, this is expected. The demos in the course are conducted using **dbt Cloud Developer licensing**, which has a slightly different interface compared to the **Team license** (which you might be using).

The interface you see may not fully match the demo due to these licensing differences. However, the core functionality remains the same, and you should still be able to follow along with the course materials.

For more details, you can refer to the FAQ entry here:
[**dbt Cloud Developer**](https://github.com/DataTalksClub/faq/blob/main/_questions/data-engineering-zoomcamp/module-4/002_44ff6ae3df_dbt-cloud-developer.md)

What are the prerequisites for taking the data engineering course?
To get the most out of the **Data Engineering Zoomcamp** course, you should have:

- **Basic coding experience**
- **Familiarity with SQL**
- **Experience with Python** (helpful but not required)

No prior data engineering experience is necessary.

For more details, you can refer to the [course prerequisites on GitHub](https://github.com/DataTalksClub/data-engineering-zoomcamp/blob/main/README.md#prerequisites).

Source: [faq-main/_questions/data-engineering-zoomcamp/general/002_bfafa427b3_course-what-are-the-prerequisites-for-this-course.md](https://github.com/DataTalksClub/faq/blob/main/_questions/data-engineering-zoomcamp/general/002_bfafa427b3_course-what-are-the-prerequisites-for-this-course.md)

I heard that the tools used in the course change every year. What tools are being used in the 2025 edition of the data engineering course?
For the **2025 edition of the Data Engineering Zoomcamp**, the tools and technologies used are updated and vary across modules. While the search results did not provide a direct list of all tools for 2025, you can explore the **official GitHub repository** for the most accurate and detailed information about the tools used in each module:

- **[Data Engineering Zoomcamp 2025 GitHub Repository](https://github.com/DataTalksClub/data-engineering-zoomcamp/tree/main)**

This repository includes:
- **Module-specific tools and setups**
- **Docker configurations**
- **Cloud services** (e.g., Google BigQuery, GCS, Looker Studio, Tableau)
- **Workflow orchestration tools** (e.g., Kestra for Module 2 in 2025)
- **Data processing and transformation tools** (e.g., dbt, Python, SQL)
- **Infrastructure as code tools** (e.g., Terraform, if applicable)

For example, **Module 2 in 2025** uses **[Kestra](https://kestra.io/)** for workflow orchestration, as indicated by the dedicated YouTube playlist:
[DE Zoomcamp 2025 (Module 2 Kestra)](https://www.youtube.com/playlist?list=PLEK3H8YwZn1oPPShk2p5k3E9vO-gPnUCf)

Additionally, **BigQuery** and **GCS (Google Cloud Storage)** are prominently featured for data storage and analytics, and **BI tools like Looker Studio and Tableau** are used for visualization.

For a comprehensive list, refer to the **syllabus and setup instructions** in the [GitHub repository](https://github.com/DataTalksClub/data-engineering-zoomcamp/tree/main).

If you need details about a specific module or tool, let me know!

I'm trying to SSH into my Google Cloud VM from a Windows laptop, but I keep getting a public key error. How can I resolve this?
Based on the search results, the most common issue for a **public key error** when SSH'ing into a Google Cloud VM from a Windows laptop is related to **username mismatches** or **incorrect SSH key configuration**. Here’s how to resolve it:

---

### **1. Check the Username in Your SSH Key**
The error often occurs because the username in your SSH key does not match the username configured in the Google Cloud Console for your VM.

#### Steps to Fix:
1. **Locate Your SSH Key:**
   - Open the SSH key file (e.g., `id_rsa.pub` or `gcp.pub`) and check the username at the end of the key.
     Example:
     ```
     ssh-rsa AAAAB3NzaC1yc2EAAA... user@host
     ```
     Here, `user` is the username embedded in the key.

2. **Compare with Google Cloud Console:**
   - Go to the [Google Cloud Console](https://console.cloud.google.com/).
   - Navigate to **Compute Engine > VM Instances**.
   - Click on your VM instance and check the **SSH Keys** section.
   - Ensure the username in the SSH key matches the username you’re using to log in.

3. **Update the SSH Key:**
   - If the usernames don’t match, regenerate the SSH key with the correct username:
     ```bash
     ssh-keygen -t rsa -f ~/.ssh/gcp -C "your_google_account_username"
     ```
   - Add the new key to your VM:
     - Copy the contents of `~/.ssh/gcp.pub`.
     - In the Google Cloud Console, paste it under **VM Instances > [Your VM] > SSH Keys**.

4. **Update Your SSH Config File:**
   - Open or create the SSH config file at `~/.ssh/config` and ensure the `User` field matches the username in your SSH key:
     ```plaintext
     Host my-vm
       HostName [VM_EXTERNAL_IP]
       User your_google_account_username
       IdentityFile ~/.ssh/gcp
     ```

---

### **2. Ensure Correct Permissions for SSH Keys**
Windows sometimes has issues with file permissions for SSH keys.

#### Steps to Fix:
1. **Navigate to Your `.ssh` Folder:**
   - Open File Explorer and go to:
     ```
     C:\Users\<your_username>\.ssh
     ```

2. **Set Correct Permissions:**
   - Right-click the private key file (e.g., `gcp` or `id_rsa`).
   - Go to **Properties > Security**.
   - Ensure your user account has **Full Control** over the file.

3. **Update the SSH Config File:**
   - In your SSH config file (`~/.ssh/config`), use the **Windows-style path** for the `IdentityFile`:
     ```plaintext
     Host my-vm
       HostName [VM_EXTERNAL_IP]
       User your_google_account_username
       IdentityFile C:\Users\<your_username>\.ssh\gcp
     ```

---

### **3. Use the Correct SSH Command**
When connecting, use the correct syntax:
```bash
ssh -i ~/.ssh/gcp your_google_account_username@[VM_EXTERNAL_IP]
```
Or, if using the config file:
```bash
ssh my-vm
```

---

### **4. Temporary Workaround**
If you still face issues, you can use the **Google Cloud Console’s built-in SSH** feature:
1. Go to [Google Cloud Console](https://console.cloud.google.com/).
2. Navigate to **Compute Engine > VM Instances**.
3. Click **SSH** next to your VM instance.

---

### **References**
- [GCP: SSH public key error - multiple users / usernames](https://github.com/DataTalksClub/faq/blob/main/_questions/data-engineering-zoomcamp/module-1/102_eb759226aa_gcp-ssh-public-key-error-multiple-users-usernames.md)
- [SSH error in VS Code - “Could not establish connection to "de-zoomcamp": Permission denied (publickey).”](https://github.com/DataTalksClub/faq/blob/main/_questions/data-engineering-zoomcamp/module-2/001_7889d2bad5_ssh-error-in-vs-code-could-not-establish-connectio.md)

I'm encountering a `UnicodeDecodeError` when reading a CSV file in Python. How can I fix this issue?
To resolve a `UnicodeDecodeError` when reading a CSV file in Python, you can try the following solutions:

---

### **1. Specify the Correct Encoding**
The most common cause of this error is that the file is not encoded in UTF-8. You can try specifying a different encoding when reading the file. Common encodings include:
- `latin1` (also known as `iso-8859-1`)
- `cp1252` (Windows-1252)
- `utf-16`

#### Example:
```python
import pandas as pd

# Try reading with a different encoding
df = pd.read_csv('your_file.csv', encoding='latin1', low_memory=False)
```

---

### **2. Use `errors='replace'` or `errors='ignore'`**
If you're unsure about the encoding, you can use the `errors` parameter to handle problematic characters:
- `errors='replace'`: Replaces invalid characters with a placeholder (e.g., `�`).
- `errors='ignore'`: Skips invalid characters entirely.

#### Example:
```python
df = pd.read_csv('your_file.csv', encoding='utf-8', errors='replace')
```

---

### **3. Detect the Encoding Automatically**
You can use libraries like `chardet` to detect the file's encoding before reading it.

#### Example:
```python
import chardet

# Detect the encoding
with open('your_file.csv', 'rb') as f:
    result = chardet.detect(f.read())

# Read the file with the detected encoding
df = pd.read_csv('your_file.csv', encoding=result['encoding'])
```

---

### **4. Use `pd.read_csv` with `engine='python'`**
Sometimes, using the Python engine instead of the C engine can help avoid encoding issues.

#### Example:
```python
df = pd.read_csv('your_file.csv', engine='python')
```

---

### **5. Convert the File to UTF-8**
If possible, open the file in a text editor (e.g., Notepad++, VS Code) and save it with UTF-8 encoding. Then, try reading it again.

---

### **Reference**
The solutions above are based on common practices for handling encoding issues in Python. For more details, you can refer to the following resource:
- [Python: Invalid Start Byte Error Message](https://github.com/DataTalksClub/faq/blob/main/_questions/data-engineering-zoomcamp/module-3/041_55b6d6256f_python-invalid-start-byte-error-message.md)

We can repeat it multiple times until we have enough data. Around 100 should be good for a start, but today we can just continue with the 10 log records we already generated.

Using AI for generating test data is quite powerful. It can help us get data faster and sometimes cover edge cases we won't think about.
There are limitations too:

* AI-generated questions might not reflect real user behavior
* It may miss important edge cases that only real users encounter
* They may not capture the full complexity of real user queries

The logs are ready, so we can run evaluation on them with our evaluation agent.
First, collect all the AI-generated logs for the v2 agent:

In [63]:
eval_set = []

for log_file in LOG_DIR.glob('*.json'):
    if 'faq_agent_v2' not in log_file.name:
        continue

    log_record = load_log_file(log_file)
    if log_record['source'] != 'ai-generated':
        continue

    eval_set.append(log_record)

and evaluate them:

In [64]:
eval_results = []

for log_record in tqdm(eval_set):
    eval_result = await evaluate_log_record(eval_agent, log_record)
    eval_results.append((log_record, eval_result))

  0%|          | 0/10 [00:00<?, ?it/s]

This code:
* Loops through each AI-generated log
* Runs our evaluation agent on it
* Stores both the original log and evaluation result

There are ways to speed this up, but we won't cover them in detail here. For example, you can try this:

Don't ask for justification - this makes evaluation faster but slightly lower quality
Parallelize execution - you can ask ChatGPT how to do this with async/await

The results are collected, but we need to display them and also calculate some statistics. The best tool for doing this is Pandas. We already should have it because minsearch depends on it.

Our data is not ready to be converted to a Pandas DataFrame. We first need to transform it a little. Let’s do it:

In [65]:
rows = []

for log_record, eval_result in eval_results:
    messages = log_record['messages']

    row = {
        'file': log_record['log_file'].name,
        'question': messages[0]['parts'][0]['content'],
        'answer': messages[-1]['parts'][0]['content'],
    }

    checks = {c.check_name: c.check_pass for c in eval_result.checklist}
    row.update(checks)

    rows.append(row)

This code:
* Extracts key information from each log (file, question, answer)
* Converts the evaluation checks into a dictionary format

Now each row is a simple key-value dictionary, so we can create a DataFrame:

In [66]:
import pandas as pd

df_evals = pd.DataFrame(rows)

We can look at individual records and see which checks are False.

But it's also useful to look at the overall stats:

In [68]:
df_evals.head()

,file,question,answer,instructions_follow,instructions_avoid,answer_relevant,answer_clear,answer_citations,completeness,tool_call_search
0,faq_agent_v2_20260402_121101_4b4e77.json,How can I generate a pip-friendly `requirement...,To generate a pip-friendly `requirements.txt` ...,True,True,True,True,True,True,True
1,faq_agent_v2_20260402_121045_47f89d.json,I missed the registration deadline for the cou...,"Based on the available information, here's wha...",True,True,True,True,True,True,True
2,faq_agent_v2_20260402_121107_7595ec.json,What are the prerequisites for taking the data...,To get the most out of the **Data Engineering ...,True,True,True,True,True,True,True
3,faq_agent_v2_20260402_121104_590d2d.json,"I'm using dbt Cloud for the course, but the in...","Yes, this is expected. The demos in the course...",True,True,True,True,True,True,True
4,faq_agent_v2_20260402_121049_087bda.json,I'm getting an error with my `docker-compose.y...,The error `'service pgdatabase refers to undef...,True,True,True,True,True,True,True

In [67]:
df_evals.mean(numeric_only=True)

instructions_follow    1.0
instructions_avoid     1.0
answer_relevant        1.0
answer_clear           1.0
answer_citations       0.9
completeness           1.0
tool_call_search       1.0
dtype: float64

This tells us:
* Only 30% of responses follow instructions completely
* All responses avoid forbidden actions (good!)
* All responses are relevant and clear (great!)
* Only 30% include proper citations (needs improvement)
* 70% of responses are complete
A* ll responses use the search tool (as expected)

For us, the most important check is answer_relevant. This tells us whether the agent actually answers the user's question. If this score was low, it’d mean that our agent is not ready.

We now know how to evaluate our agent. What can we do with it now?

Many things:
* Decide if this quality is good enough for deployment
* Evaluate different chunking approaches and search
* See if changing a prompt leads to any improvements.

The algorithm is simple:
* Collect data for evaluation and keep this dataset fixed
* Run different versions of your agent for this dataset
* Compare key metrics to decide which version is better
 Evaluation is a very powerful tool and we should use it when possible.

### Evaluating functions and tools

Also, we can (and should) evaluate our tools separately from evaluating the agent.

If it's code, we need to cover it with unit and integration tests.

We also have the search function, which we can evaluate using standard information retrieval metrics. For example:
* Precision and Recall: How many relevant results were retrieved vs. how many relevant results were missed
* Hit Rate: Percentage of queries that return at least one relevant result
* MRR (Mean Reciprocal Rank): Reflects the position of the first relevant result in the ranking

This is how we can implement hitrate and MRR calculation in Python:

In [69]:
def evaluate_search_quality(search_function, test_queries):
    results = []

    for query, expected_docs in test_queries:
        search_results = search_function(query, num_results=5)

        # Calculate hit rate
        relevant_found = any(doc['filename'] in expected_docs for doc in search_results)

        # Calculate MRR
        for i, doc in enumerate(search_results):
            if doc['filename'] in expected_docs:
                mrr = 1 / (i + 1)
                break
        else:
            mrr = 0

        results.append({
            'query': query,
            'hit': relevant_found,
            'mrr': mrr
        })
    return results

These ideas and the code will be useful when you implement a real agent project with search.
It's useful because it'll helps us make guided decisions about:
* When to use text vs. vector vs. hybrid search
* What are the best parameters for our search